import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const LEGACY_BADGES=[
  {key:"first-footstep",icon:"🥾",name:"First Footstep",desc:"Log your first outdoor activity",requirement:1,metric:"activities"},{key:"state-explorer",icon:"🧭",name:"State Explorer",desc:"Visit 3 different Malaysian states",requirement:3,metric:"states"},{key:"malaysia-wanderer",icon:"🗺️",name:"Malaysia Wanderer",desc:"Visit 5 different Malaysian states",requirement:5,metric:"states"},{key:"hidden-gem-hunter",icon:"💎",name:"Hidden Gem Hunter",desc:"Visit 3 hidden-gem locations",requirement:3,metric:"gems"},{key:"first-contribution",icon:"✍️",name:"First Contribution",desc:"Write your first community review",requirement:1,metric:"reviews"},{key:"local-storyteller",icon:"📖",name:"Local Storyteller",desc:"Write 3 community reviews",requirement:3,metric:"reviews"},{key:"trusted-contributor",icon:"✅",name:"Trusted Contributor",desc:"Write 5 community reviews",requirement:5,metric:"reviews"},{key:"community-favourite",icon:"⭐",name:"Community Favourite",desc:"Write 10 community reviews",requirement:10,metric:"reviews"},{key:"malaysia-insider",icon:"🏆",name:"Malaysia Insider",desc:"Log 100 km of outdoor activities",requirement:100,metric:"km"},
];
const BADGE_METRICS=new Set(["activities","states","km","gems","reviews","hikes","dives","cycleKm","camps"]);
function badgeDefinition(row:any){return{id:row.id||row.key,key:row.badge_key||row.key,name:row.name,desc:row.description||row.desc||"",description:row.description||row.desc||"",nameMs:row.name_ms||"",descriptionMs:row.description_ms||"",nameZh:row.name_zh||"",descriptionZh:row.description_zh||"",icon:row.icon||"",imageUrl:row.image_url||"",metric:row.metric,requirement:Number(row.requirement),displayOrder:Number(row.display_order||0),status:row.status||"active",isSystem:row.is_system===true,createdAt:row.created_at||null,updatedAt:row.updated_at||null}}
function reply(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json"}})}
function clean(value:unknown,max=2000){return String(value??"").trim().slice(0,max)}
function httpError(message:string,status:number){return Object.assign(new Error(message),{status})}
const MAX_REVIEW_WORDS=300;
function reviewComment(value:unknown){return String(value??"").trim()}
function countWords(value:string){return value.match(/\S+/g)?.length??0}
async function shareTokenHash(token:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return Array.from(new Uint8Array(bytes)).map(value=>value.toString(16).padStart(2,"0")).join("")}
function newShareToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function verifyUser(request:Request){const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)throw httpError("Please sign in first.",401);const key=Deno.env.get("FIREBASE_WEB_API_KEY");if(!key)throw new Error("Firebase authentication is not configured.");const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${key}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken:token})});if(!r.ok)throw httpError("Your login session is invalid or expired.",401);const user=(await r.json()).users?.[0];if(!user?.localId)throw httpError("Firebase user not found.",401);return user}
async function requireAdmin(request:Request,uid:string){const project=clean(Deno.env.get("FIREBASE_PROJECT_ID"),100),token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const r=await fetch(`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(project)}/databases/(default)/documents/User/${encodeURIComponent(uid)}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error("Unable to verify administrator access.");const profile=await r.json();if(fromFs(profile.fields?.role)!=="admin")throw new Error("Administrator access is required.")}
async function requireActiveUser(request:Request,uid:string){const project=clean(Deno.env.get("FIREBASE_PROJECT_ID"),100),token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const r=await fetch(`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(project)}/databases/(default)/documents/User/${encodeURIComponent(uid)}`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===404)return;if(!r.ok)throw new Error("Unable to verify account status.");const profile=await r.json(),status=fromFs(profile.fields?.status);if(status==="deleted"||status==="disabled")throw new Error("This account has been disabled by an administrator.")}
function fromFs(v:any):any{if(!v)return null;if("nullValue"in v)return null;if("stringValue"in v)return v.stringValue;if("integerValue"in v)return Number(v.integerValue);if("doubleValue"in v)return Number(v.doubleValue);if("booleanValue"in v)return v.booleanValue;if("arrayValue"in v)return(v.arrayValue.values||[]).map(fromFs);if("mapValue"in v)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,fromFs(x)]));return null}
async function location(id:string){const project=clean(Deno.env.get("FIREBASE_PROJECT_ID"),100);if(!project)throw new Error("Firebase project ID is not configured.");const r=await fetch(`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(project)}/databases/(default)/documents/Location/${encodeURIComponent(id)}`);if(r.status===404)return null;if(!r.ok)throw new Error("Unable to verify the selected location.");const d=await r.json();return{id,...Object.fromEntries(Object.entries(d.fields||{}).map(([k,v])=>[k,fromFs(v)]))}}
function fallbackLocation(data:any,id:string){const source=data?.locationSnapshot||data?.location||{};const name=clean(source.name||data.locationName,180),state=clean(source.state,80),activity=clean(source.activity,80);if(!name)return null;return{id,name,state,activity,is_hidden_gem:source.is_hidden_gem===true||source.isHiddenGem===true}}
function sharedLocation(row:any){return{id:clean(row.id,128),name:clean(row.name,180),address:clean(row.address,300),state:clean(row.state,80),activity:clean(row.activity,80),difficulty:clean(row.difficulty,40),emoji:clean(row.emoji,16),imageUrl:clean(row.image_url||row.imageUrl,1000)}}
async function optionalViewerUid(request:Request){try{return(await verifyUser(request)).localId||null}catch{return null}}
async function firebaseSystemRole(request:Request,uid:string){const project=clean(Deno.env.get("FIREBASE_PROJECT_ID"),100),token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!project||!token)return"user";const r=await fetch(`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(project)}/databases/(default)/documents/User/${encodeURIComponent(uid)}`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===404)return"user";if(!r.ok)throw new Error("Unable to verify account role.");const profile=await r.json();return fromFs(profile.fields?.role)==="admin"?"admin":"user"}
async function removeInvalidAdminMemberships(db:any,uid:string){const{error}=await db.from("seekmy_bookmark_folder_members").delete().eq("firebase_uid",uid);if(error)throw new Error(error.message)}
async function folderMembership(db:any,folderId:string,uid:string){const{data,error}=await db.from("seekmy_bookmark_folder_members").select("id,role,display_name").eq("folder_share_id",folderId).eq("firebase_uid",uid).maybeSingle();if(error)throw new Error(error.message);return data}
async function requireFolderMember(db:any,folderId:string,uid:string){const member=await folderMembership(db,folderId,uid);if(!member)throw new Error("You are not a member of this shared folder.");return member}
async function requireFolderOwner(db:any,folderId:string,uid:string){const member=await requireFolderMember(db,folderId,uid);if(member.role!=="owner")throw new Error("Only the folder owner can perform this action.");return member}
async function collaborativeFolder(db:any,share:any,viewerUid:string|null){const[{data:items,error:itemError},{count,error:countError}]=await Promise.all([db.from("seekmy_bookmark_folder_locations").select("location_id,location,added_by,added_at").eq("folder_share_id",share.id).order("added_at",{ascending:true}),db.from("seekmy_bookmark_folder_members").select("id",{count:"exact",head:true}).eq("folder_share_id",share.id)]);if(itemError||countError)throw new Error(itemError?.message||countError?.message);const viewer=viewerUid?await folderMembership(db,share.id,viewerUid):null;return{id:share.id,personalFolderId:share.personal_folder_id||null,name:share.folder_name,sharingEnabled:share.enabled===true,memberCount:count||0,viewerRole:viewer?.role||null,locations:(items||[]).map((item:any)=>({...item.location,addedByMe:Boolean(viewerUid&&item.added_by===viewerUid),canRemove:viewer?.role==="owner"||Boolean(viewerUid&&item.added_by===viewerUid)}))}}
function backendDb(){
  const url=Deno.env.get("SUPABASE_URL");
  const serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if(!url||!serviceRoleKey)throw new Error("Supabase service role is not configured. Add SUPABASE_SERVICE_ROLE_KEY to Edge Function secrets.");
  return createClient(url,serviceRoleKey,{auth:{persistSession:false},global:{headers:{Authorization:`Bearer ${serviceRoleKey}`}}});
}
async function badgeDefinitions(db:any,includeArchived=false){const query=db.from("seekmy_badge_definitions").select("*").order("display_order",{ascending:true}).order("created_at",{ascending:true});if(!includeArchived)query.eq("status","active");const{data,error}=await query;if(error||!data?.length){if(includeArchived&&error)throw new Error(error.message);return LEGACY_BADGES.map((badge,index)=>badgeDefinition({...badge,id:badge.key,badge_key:badge.key,description:badge.desc,display_order:(index+1)*10,status:"active",is_system:true}))}return data.map(badgeDefinition)}
function badgePayload(data:any){const key=clean(data.key||data.badgeKey,80).toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-+|-+$/g,"");const name=clean(data.name,100),description=clean(data.description||data.desc,300),metric=clean(data.metric,30),requirement=Number(data.requirement),displayOrder=Math.trunc(Number(data.displayOrder||0));if(!key||key.length<3)throw httpError("Badge key must contain at least 3 letters, numbers, or hyphens.",400);if(!name||!description)throw httpError("Badge name and description are required.",400);if(!BADGE_METRICS.has(metric))throw httpError("Choose a supported badge metric.",400);if(!Number.isFinite(requirement)||requirement<=0||requirement>100000)throw httpError("Badge requirement must be greater than 0.",400);return{badge_key:key,name,description,name_ms:clean(data.nameMs,100),description_ms:clean(data.descriptionMs,300),name_zh:clean(data.nameZh,100),description_zh:clean(data.descriptionZh,300),icon:clean(data.icon,20),image_url:clean(data.imageUrl,1000),metric,requirement,display_order:Number.isFinite(displayOrder)?displayOrder:0}}
function activity(row:any){return{id:row.id,userId:row.firebase_uid,userName:row.user_name||"Explorer",created_by_id:row.firebase_uid,created_by:row.user_name||"Explorer",locationId:row.location_id,location:row.location_name,state:row.state,activity:row.activity,is_hidden_gem:row.is_hidden_gem===true,isHiddenGem:row.is_hidden_gem===true,distance:Number(row.distance_km),duration:row.duration,date:row.activity_date,notes:row.notes,comment:row.comment,photoUrl:row.photo_url,status:row.status||"approved",rejectionReason:row.rejection_reason||"",reviewedAt:row.reviewed_at||"",created_date:row.created_at}}
function review(row:any){return{id:row.id,locationId:row.location_id,locationName:row.location_name,userId:row.firebase_uid,userName:row.user_name,rating:row.rating,comment:row.comment,photoUrl:row.photo_url||"",status:row.status,flagReason:row.flag_reason,flaggedBy:row.flagged_by||[],date:new Date(row.created_at).toLocaleDateString("en-MY",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Kuala_Lumpur"}),created_date:row.created_at,updated_date:row.updated_at}}
function withinReviewEditWindow(row:any){return Date.now()-new Date(row.created_at).getTime()<=24*60*60*1000}
async function sync(db:any,uid:string,name:string){const[{data:logs,error:a},{data:reviews,error:b},{data:old,error:c},definitions]=await Promise.all([db.from("seekmy_activities").select("activity,state,distance_km,is_hidden_gem").eq("firebase_uid",uid).eq("status","approved"),db.from("seekmy_reviews").select("id").eq("firebase_uid",uid).not("status","in",'(removed,rejected)'),db.from("seekmy_badges").select("badge_key").eq("firebase_uid",uid),badgeDefinitions(db)]);if(a||b||c)throw new Error(a?.message||b?.message||c?.message);const m:any={activities:logs.length,hikes:logs.filter((x:any)=>/hike/i.test(x.activity)).length,dives:logs.filter((x:any)=>/div/i.test(x.activity)).length,states:new Set(logs.map((x:any)=>x.state).filter(Boolean)).size,km:logs.reduce((s:number,x:any)=>s+Number(x.distance_km||0),0),gems:logs.filter((x:any)=>x.is_hidden_gem).length,reviews:reviews.length,cycleKm:logs.filter((x:any)=>/cycl/i.test(x.activity)).reduce((s:number,x:any)=>s+Number(x.distance_km||0),0),camps:logs.filter((x:any)=>/camp/i.test(x.activity)).length};const earned=definitions.filter((x:any)=>m[x.metric]>=x.requirement),earnedKeys=new Set(earned.map((x:any)=>x.key)),keys=new Set(old.map((x:any)=>x.badge_key)),fresh=earned.filter((x:any)=>!keys.has(x.key)),activeDefinitionKeys=new Set(definitions.map((x:any)=>x.key)),revoked=old.filter((x:any)=>activeDefinitionKeys.has(x.badge_key)&&!earnedKeys.has(x.badge_key)).map((x:any)=>x.badge_key);if(fresh.length){const{error}=await db.from("seekmy_badges").upsert(fresh.map((x:any)=>({firebase_uid:uid,badge_key:x.key,name:x.name,description:x.desc,icon:x.icon,progress:m[x.metric]})));if(error)throw new Error(error.message)}if(revoked.length){const{error}=await db.from("seekmy_badges").delete().eq("firebase_uid",uid).in("badge_key",revoked);if(error)throw new Error(error.message)}const stats={total_km:Math.round(m.km*100)/100,checkins:logs.length,states:m.states};const{error}=await db.from("seekmy_user_stats").upsert({firebase_uid:uid,display_name:name,...stats,updated_at:new Date().toISOString()});if(error)throw new Error(error.message);return{stats,newBadges:fresh,revokedBadges:revoked}}

Deno.serve(async request=>{if(request.method==="OPTIONS")return new Response("ok",{headers:CORS});if(request.method!=="POST")return reply({error:"Method not allowed."},405);try{const body=await request.json(),action=clean(body.action,40),data=body.payload||{};
  if(action==="getWeather"){const key=Deno.env.get("OPENWEATHER_API_KEY");if(!key)return reply({error:"Weather is not configured."},503);const p=new URLSearchParams({appid:key,units:"metric"}),lat=Number(data.lat),lng=Number(data.lng),hasCoords=Number.isFinite(lat)&&Number.isFinite(lng);if(hasCoords){p.set("lat",String(lat));p.set("lon",String(lng))}else p.set("q",`${clean(data.locationName||data.state,120)||"Kuala Lumpur"},MY`);const[a,b,c]=await Promise.all([fetch(`https://api.openweathermap.org/data/2.5/weather?${p}`),fetch(`https://api.openweathermap.org/data/2.5/forecast?${p}`),hasCoords?fetch(`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(String(lat))}&longitude=${encodeURIComponent(String(lng))}&hourly=uv_index&forecast_days=1&timezone=Asia%2FKuala_Lumpur`).catch(()=>null):Promise.resolve(null)]);if(!a.ok||!b.ok)return reply({error:"Weather data is unavailable."},503);const uvJson=c?.ok?await c.json().catch(()=>null):null,times=Array.isArray(uvJson?.hourly?.time)?uvJson.hourly.time:[],values=Array.isArray(uvJson?.hourly?.uv_index)?uvJson.hourly.uv_index.map(Number):[],now=Date.now(),idx=times.reduce((best:number,time:string,index:number)=>{const d=Math.abs(new Date(`${time}:00+08:00`).getTime()-now),bd=best>=0?Math.abs(new Date(`${times[best]}:00+08:00`).getTime()-now):Number.POSITIVE_INFINITY;return d<bd?index:best},-1),raw=idx>=0?values[idx]:NaN,uv=Number.isFinite(raw)?Math.round(raw*10)/10:null;return reply({current:await a.json(),forecast:await b.json(),uv:{value:uv}})}
  const db=backendDb();
  if(action==="getBadgeDefinitions")return reply({badges:await badgeDefinitions(db)});
  if(action==="getSharedBookmarkFolder"){
    const token=clean(data.token,200);
    if(token.length<32)return reply({error:"This shared folder is unavailable or sharing was disabled."},404);
    const tokenHash=await shareTokenHash(token),{data:share,error}=await db.from("seekmy_bookmark_folder_shares").select("id,folder_name,enabled").eq("token_hash",tokenHash).eq("enabled",true).maybeSingle();
    if(error)throw new Error(error.message);
    if(!share)return reply({error:"This shared folder is unavailable or sharing was disabled."},404);
    let viewerUid=await optionalViewerUid(request);
    if(viewerUid&&await firebaseSystemRole(request,viewerUid)==="admin"){await removeInvalidAdminMemberships(db,viewerUid);viewerUid=null}
    return reply({folder:await collaborativeFolder(db,share,viewerUid)});
  }
  if(action==="getReviews"){const{data:rows,error}=await db.from("seekmy_reviews").select("*").eq("location_id",clean(data.locationId,128)).eq("status","approved").order("created_at",{ascending:false});if(error)throw new Error(error.message);return reply({reviews:rows.map(review)})}
  if(action==="getLocationReviewSummaries"){const{data:rows,error}=await db.from("seekmy_reviews").select("location_id,location_name,rating").eq("status","approved");if(error)throw new Error(error.message);const grouped=new Map();for(const row of rows||[]){const key=String(row.location_id),current=grouped.get(key)||{locationId:key,locationName:row.location_name||"",count:0,total:0};current.count+=1;current.total+=Number(row.rating||0);if(row.location_name)current.locationName=row.location_name;grouped.set(key,current)}return reply({summaries:[...grouped.values()].map(x=>({locationId:x.locationId,locationName:x.locationName,count:x.count,rating:Math.round((x.total/x.count)*10)/10}))})}
  if(action==="getLeaderboard"){const period=data.period==="monthly"?"monthly":"weekly",startDate=clean(data.startDate,10),endDate=clean(data.endDate,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(startDate)||!/^\d{4}-\d{2}-\d{2}$/.test(endDate)||startDate>endDate)return reply({error:"Choose a valid leaderboard date range."},400);const maxDays=period==="weekly"?7:31,start=new Date(`${startDate}T00:00:00Z`),end=new Date(`${endDate}T00:00:00Z`),days=Math.round((end.getTime()-start.getTime())/86400000)+1;if(days<1||days>maxDays)return reply({error:"Leaderboard date range does not match the selected period."},400);const[{data:logs,error:a},{data:stats,error:b},definitions]=await Promise.all([db.from("seekmy_activities").select("firebase_uid,state,distance_km").eq("status","approved").gte("activity_date",startDate).lte("activity_date",endDate),db.from("seekmy_user_stats").select("firebase_uid,display_name"),badgeDefinitions(db)]);if(a||b)throw new Error(a?.message||b?.message);const names=new Map((stats||[]).map((x:any)=>[x.firebase_uid,x.display_name])),totals=new Map();for(const x of logs||[]){const row=totals.get(x.firebase_uid)||{id:x.firebase_uid,name:names.get(x.firebase_uid)||"Explorer",km:0,checkins:0,stateSet:new Set()};row.km+=Number(x.distance_km||0);row.checkins++;if(x.state)row.stateSet.add(x.state);totals.set(x.firebase_uid,row)}return reply({entries:[...totals.values()].map(x=>({id:x.id,name:x.name,km:Math.round(x.km*100)/100,checkins:x.checkins,states:x.stateSet.size})),badges:definitions,period,startDate,endDate})}
  const user=await verifyUser(request),uid=user.localId,name=user.displayName||user.email?.split("@")[0]||"Explorer";await requireActiveUser(request,uid);
  if(action==="getAdminBadgeDefinitions"){await requireAdmin(request,uid);const definitions=await badgeDefinitions(db,true);const{data:earned,error}=await db.from("seekmy_badges").select("badge_key");if(error)throw new Error(error.message);const counts=new Map<string,number>();for(const row of earned||[])counts.set(row.badge_key,(counts.get(row.badge_key)||0)+1);return reply({badges:definitions.map((badge:any)=>({...badge,earnedCount:counts.get(badge.key)||0}))})}
  if(action==="createBadgeDefinition"){await requireAdmin(request,uid);const payload=badgePayload(data);const{data:row,error}=await db.from("seekmy_badge_definitions").insert({...payload,status:"active",is_system:false,created_by:uid,updated_by:uid}).select().single();if(error?.code==="23505")return reply({error:"A badge with this key already exists."},409);if(error)throw new Error(error.message);return reply({badge:badgeDefinition(row)},201)}
  if(action==="updateBadgeDefinition"){await requireAdmin(request,uid);const id=clean(data.id,80),{data:existing,error:readError}=await db.from("seekmy_badge_definitions").select("*").eq("id",id).single();if(readError)return reply({error:"Badge definition not found."},404);const payload=badgePayload({...data,key:existing.badge_key});const{data:row,error}=await db.from("seekmy_badge_definitions").update({...payload,badge_key:existing.badge_key,updated_by:uid,updated_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw new Error(error.message);return reply({badge:badgeDefinition(row)})}
  if(action==="archiveBadgeDefinition"||action==="restoreBadgeDefinition"){await requireAdmin(request,uid);const id=clean(data.id,80),status=action==="restoreBadgeDefinition"?"active":"archived";const{data:row,error}=await db.from("seekmy_badge_definitions").update({status,updated_by:uid,updated_at:new Date().toISOString()}).eq("id",id).select().single();if(error)return reply({error:"Badge definition not found."},404);return reply({badge:badgeDefinition(row)})}
  const collaborativeActions=new Set(["getBookmarkFolderShareStatus","createBookmarkFolderShare","disableBookmarkFolderShare","getMyCollaborativeFolders","joinSharedBookmarkFolder","addSharedBookmarkLocation","removeSharedBookmarkLocation","renameSharedBookmarkFolder","deleteSharedBookmarkFolder","leaveSharedBookmarkFolder","getSharedBookmarkFolderMembers","removeSharedBookmarkFolderMember"]);
  if(collaborativeActions.has(action)&&await firebaseSystemRole(request,uid)==="admin"){
    await removeInvalidAdminMemberships(db,uid);
    if(action==="getMyCollaborativeFolders")return reply({folders:[]});
    return reply({error:"Collaborative bookmark folders are available for user accounts only."},403);
  }
  if(action==="cleanupAdminCollaborativeMemberships"){
    await requireAdmin(request,uid);
    const{data:membershipRows,error:membershipError}=await db.from("seekmy_bookmark_folder_members").select("id,firebase_uid");if(membershipError)throw new Error(membershipError.message);const uniqueUids=[...new Set((membershipRows||[]).map((row:any)=>row.firebase_uid).filter(Boolean))],roleRows=await Promise.all(uniqueUids.map(async(memberUid:string)=>({uid:memberUid,role:await firebaseSystemRole(request,memberUid)}))),adminUids=roleRows.filter((row:any)=>row.role==="admin").map((row:any)=>row.uid);if(!adminUids.length)return reply({success:true,removedMemberships:0});const invalidRows=(membershipRows||[]).filter((row:any)=>adminUids.includes(row.firebase_uid)),{error:cleanupError}=await db.from("seekmy_bookmark_folder_members").delete().in("id",invalidRows.map((row:any)=>row.id));if(cleanupError)throw new Error(cleanupError.message);return reply({success:true,removedMemberships:invalidRows.length});
  }
  if(action==="getBookmarkFolderShareStatus"){
    const personalFolderId=clean(data.personalFolderId,200),folderName=clean(data.folderName,80),folderKey=folderName.toLowerCase();if(!personalFolderId)return reply({error:"Personal folder ID is required."},400);
    let{data:share,error}=await db.from("seekmy_bookmark_folder_shares").select("id,enabled,updated_at,personal_folder_id").eq("firebase_uid",uid).eq("personal_folder_id",personalFolderId).maybeSingle();if(error)throw new Error(error.message);
    if(!share&&folderName){const legacy=await db.from("seekmy_bookmark_folder_shares").select("id,enabled,updated_at,personal_folder_id").eq("firebase_uid",uid).eq("folder_key",folderKey).is("personal_folder_id",null).maybeSingle();if(legacy.error)throw new Error(legacy.error.message);share=legacy.data;if(share){const{error:adoptError}=await db.from("seekmy_bookmark_folder_shares").update({personal_folder_id:personalFolderId}).eq("id",share.id);if(adoptError)throw new Error(adoptError.message)}}
    return reply({active:share?.enabled===true,folderId:share?.id||null,updatedAt:share?.updated_at||null});
  }
  if(action==="createBookmarkFolderShare"){
    let folderName=clean(data.folderName,80);const personalFolderId=clean(data.personalFolderId,200),sharedFolderId=clean(data.sharedFolderId,80),folderKey=folderName.toLowerCase(),locationIds=[...new Set((Array.isArray(data.locationIds)?data.locationIds:[]).map((value:unknown)=>clean(value,128)).filter(Boolean))].slice(0,100);
    if(!folderName||folderName==="All"||folderName==="Uncategorized")return reply({error:"Choose a real bookmark folder to share."},400);
    if(!personalFolderId&&!sharedFolderId)return reply({error:"Folder identity is required."},400);
    if(!locationIds.length)return reply({error:"Add at least one location to this folder before sharing it."},400);
    if(personalFolderId){const{data:memberRows,error:memberReadError}=await db.from("seekmy_bookmark_folder_members").select("folder_share_id").eq("firebase_uid",uid);if(memberReadError)throw new Error(memberReadError.message);const memberFolderIds=(memberRows||[]).map((row:any)=>row.folder_share_id);if(memberFolderIds.length){const{data:sameNameRows,error:sameNameError}=await db.from("seekmy_bookmark_folder_shares").select("id,personal_folder_id").in("id",memberFolderIds).eq("folder_key",folderKey);if(sameNameError)throw new Error(sameNameError.message);if((sameNameRows||[]).some((row:any)=>row.personal_folder_id!==personalFolderId))return reply({error:"A folder with this name already exists. Please choose another name."},409)}}
    const resolved=await Promise.all(locationIds.map((id:string)=>location(id).catch(()=>null))),locations=resolved.filter(Boolean).map(sharedLocation);
    if(!locations.length)return reply({error:"No available locations were found in this folder."},400);
    const token=newShareToken(),tokenHash=await shareTokenHash(token),now=new Date().toISOString();let share:any;
    if(sharedFolderId){await requireFolderOwner(db,sharedFolderId,uid);const existing=await db.from("seekmy_bookmark_folder_shares").select("id,folder_name,enabled").eq("id",sharedFolderId).single();if(existing.error)throw new Error(existing.error.message);folderName=existing.data.folder_name;const updated=await db.from("seekmy_bookmark_folder_shares").update({token_hash:tokenHash,locations,enabled:true,updated_at:now}).eq("id",sharedFolderId).select("id,folder_name,enabled").single();if(updated.error)throw new Error(updated.error.message);share=updated.data}
    else{let existing=await db.from("seekmy_bookmark_folder_shares").select("id,folder_name,enabled").eq("firebase_uid",uid).eq("personal_folder_id",personalFolderId).maybeSingle();if(existing.error)throw new Error(existing.error.message);if(!existing.data){const legacy=await db.from("seekmy_bookmark_folder_shares").select("id,folder_name,enabled").eq("firebase_uid",uid).eq("folder_key",folderKey).is("personal_folder_id",null).maybeSingle();if(legacy.error)throw new Error(legacy.error.message);existing=legacy}if(existing.data){const updated=await db.from("seekmy_bookmark_folder_shares").update({personal_folder_id:personalFolderId,folder_key:folderKey,folder_name:folderName,token_hash:tokenHash,locations,enabled:true,updated_at:now}).eq("id",existing.data.id).select("id,folder_name,enabled").single();if(updated.error)throw new Error(updated.error.message);share=updated.data}else{const inserted=await db.from("seekmy_bookmark_folder_shares").insert({firebase_uid:uid,personal_folder_id:personalFolderId,folder_key:folderKey,folder_name:folderName,token_hash:tokenHash,locations,enabled:true,updated_at:now}).select("id,folder_name,enabled").single();if(inserted.error)throw new Error(inserted.error.message);share=inserted.data}}
    const{error:memberError}=await db.from("seekmy_bookmark_folder_members").upsert({folder_share_id:share.id,firebase_uid:uid,display_name:clean(name,120)||"Explorer",role:"owner"},{onConflict:"folder_share_id,firebase_uid"});
    if(memberError)throw new Error(memberError.message);
    const{error:locationError}=await db.from("seekmy_bookmark_folder_locations").upsert(locations.map((item:any)=>({folder_share_id:share.id,location_id:String(item.id),location:item,added_by:uid})),{onConflict:"folder_share_id,location_id"});
    if(locationError)throw new Error(locationError.message);
    return reply({token,folderId:share.id,folderName,locationCount:locations.length});
  }
  if(action==="disableBookmarkFolderShare"){
    let folderId=clean(data.folderId,80);
    if(folderId)await requireFolderOwner(db,folderId,uid);
    else{const personalFolderId=clean(data.personalFolderId,200);if(!personalFolderId)return reply({error:"Folder identity is required."},400);const{data:share,error:readError}=await db.from("seekmy_bookmark_folder_shares").select("id").eq("firebase_uid",uid).eq("personal_folder_id",personalFolderId).maybeSingle();if(readError)throw new Error(readError.message);if(!share)return reply({error:"Shared folder not found."},404);folderId=share.id}
    const{error}=await db.from("seekmy_bookmark_folder_shares").update({enabled:false,updated_at:new Date().toISOString()}).eq("id",folderId);
    if(error)throw new Error(error.message);
    return reply({success:true});
  }
  if(action==="getMyCollaborativeFolders"){
    const{data:memberships,error:membershipError}=await db.from("seekmy_bookmark_folder_members").select("folder_share_id,role").eq("firebase_uid",uid).order("joined_at",{ascending:true});
    if(membershipError)throw new Error(membershipError.message);
    const ids=(memberships||[]).map((item:any)=>item.folder_share_id);
    if(!ids.length)return reply({folders:[]});
    const{data:shares,error}=await db.from("seekmy_bookmark_folder_shares").select("id,personal_folder_id,folder_name,enabled,updated_at").in("id",ids);
    if(error)throw new Error(error.message);
    return reply({folders:await Promise.all((shares||[]).map((share:any)=>collaborativeFolder(db,share,uid)))});
  }
  if(action==="joinSharedBookmarkFolder"){
    const token=clean(data.token,200);
    if(token.length<32)return reply({error:"This shared folder is unavailable or sharing was disabled."},404);
    const tokenHash=await shareTokenHash(token),{data:share,error}=await db.from("seekmy_bookmark_folder_shares").select("id,folder_name,folder_key,enabled,firebase_uid").eq("token_hash",tokenHash).eq("enabled",true).maybeSingle();
    if(error)throw new Error(error.message);if(!share)return reply({error:"This shared folder is unavailable or sharing was disabled."},404);
    const existingMember=await folderMembership(db,share.id,uid);if(!existingMember){const{data:memberRows,error:memberReadError}=await db.from("seekmy_bookmark_folder_members").select("folder_share_id").eq("firebase_uid",uid);if(memberReadError)throw new Error(memberReadError.message);const otherIds=(memberRows||[]).map((row:any)=>row.folder_share_id).filter((id:string)=>id!==share.id);if(otherIds.length){const{count,error:duplicateError}=await db.from("seekmy_bookmark_folder_shares").select("id",{count:"exact",head:true}).in("id",otherIds).eq("folder_key",share.folder_key);if(duplicateError)throw new Error(duplicateError.message);if(count)return reply({error:"A folder with this name already exists. Please choose another folder name first."},409)}}const role=share.firebase_uid===uid?"owner":"member",{error:joinError}=await db.from("seekmy_bookmark_folder_members").upsert({folder_share_id:share.id,firebase_uid:uid,display_name:clean(name,120)||"Explorer",role},{onConflict:"folder_share_id,firebase_uid"});
    if(joinError)throw new Error(joinError.message);
    return reply({folderId:share.id,folderName:share.folder_name,role,alreadyJoined:Boolean(existingMember)});
  }
  if(action==="addSharedBookmarkLocation"){
    const folderId=clean(data.folderId,80),locationId=clean(data.locationId,128);await requireFolderMember(db,folderId,uid);
    const resolved=(await location(locationId).catch(()=>null))||fallbackLocation(data,locationId);if(!resolved)return reply({error:"Location not found."},404);const snapshot=sharedLocation(resolved);
    const{error}=await db.from("seekmy_bookmark_folder_locations").upsert({folder_share_id:folderId,location_id:locationId,location:snapshot,added_by:uid},{onConflict:"folder_share_id,location_id",ignoreDuplicates:true});if(error)throw new Error(error.message);
    await db.from("seekmy_bookmark_folder_shares").update({updated_at:new Date().toISOString()}).eq("id",folderId);
    return reply({location:{...snapshot,addedByMe:true,canRemove:true}});
  }
  if(action==="removeSharedBookmarkLocation"){
    const folderId=clean(data.folderId,80),locationId=clean(data.locationId,128),member=await requireFolderMember(db,folderId,uid),{data:item,error:readError}=await db.from("seekmy_bookmark_folder_locations").select("added_by").eq("folder_share_id",folderId).eq("location_id",locationId).maybeSingle();
    if(readError)throw new Error(readError.message);if(!item)return reply({error:"Location is not in this shared folder."},404);if(member.role!=="owner"&&item.added_by!==uid)return reply({error:"Members can only remove locations they added."},403);
    const{error}=await db.from("seekmy_bookmark_folder_locations").delete().eq("folder_share_id",folderId).eq("location_id",locationId);if(error)throw new Error(error.message);return reply({success:true});
  }
  if(action==="renameSharedBookmarkFolder"){
    const folderId=clean(data.folderId,80),folderName=clean(data.folderName,80);await requireFolderOwner(db,folderId,uid);if(!folderName||folderName==="All"||folderName==="Uncategorized")return reply({error:"Enter a valid shared folder name."},400);
    const{error}=await db.from("seekmy_bookmark_folder_shares").update({folder_name:folderName,folder_key:folderName.toLowerCase(),updated_at:new Date().toISOString()}).eq("id",folderId);if(error)throw new Error(error.message);return reply({success:true,folderName});
  }
  if(action==="deleteSharedBookmarkFolder"){const folderId=clean(data.folderId,80);await requireFolderOwner(db,folderId,uid);const{error}=await db.from("seekmy_bookmark_folder_shares").delete().eq("id",folderId);if(error)throw new Error(error.message);return reply({success:true})}
  if(action==="leaveSharedBookmarkFolder"){const folderId=clean(data.folderId,80),member=await requireFolderMember(db,folderId,uid);if(member.role==="owner")return reply({error:"The owner cannot leave. Delete the shared folder instead."},409);const{error}=await db.from("seekmy_bookmark_folder_members").delete().eq("folder_share_id",folderId).eq("firebase_uid",uid);if(error)throw new Error(error.message);return reply({success:true})}
  if(action==="getSharedBookmarkFolderMembers"){
    const folderId=clean(data.folderId,80),viewer=await requireFolderMember(db,folderId,uid),{data:members,error}=await db.from("seekmy_bookmark_folder_members").select("id,firebase_uid,display_name,role,joined_at").eq("folder_share_id",folderId).order("joined_at",{ascending:true});if(error)throw new Error(error.message);const roles=await Promise.all((members||[]).map(async(member:any)=>({member,systemRole:await firebaseSystemRole(request,member.firebase_uid)}))),invalidIds=roles.filter((item:any)=>item.systemRole==="admin").map((item:any)=>item.member.id);if(invalidIds.length){const{error:cleanupError}=await db.from("seekmy_bookmark_folder_members").delete().in("id",invalidIds);if(cleanupError)throw new Error(cleanupError.message)}return reply({viewerRole:viewer.role,members:roles.filter((item:any)=>item.systemRole!=="admin").map((item:any)=>({id:item.member.id,display_name:item.member.display_name,role:item.member.role,joined_at:item.member.joined_at}))});
  }
  if(action==="removeSharedBookmarkFolderMember"){
    const folderId=clean(data.folderId,80),membershipId=clean(data.membershipId,80);await requireFolderOwner(db,folderId,uid);const{data:target,error:readError}=await db.from("seekmy_bookmark_folder_members").select("role").eq("id",membershipId).eq("folder_share_id",folderId).maybeSingle();if(readError)throw new Error(readError.message);if(!target)return reply({error:"Member not found."},404);if(target.role==="owner")return reply({error:"The folder owner cannot be removed."},403);const{error}=await db.from("seekmy_bookmark_folder_members").delete().eq("id",membershipId).eq("folder_share_id",folderId);if(error)throw new Error(error.message);return reply({success:true});
  }
  if(action==="getAdminReviews"){await requireAdmin(request,uid);const{data:rows,error}=await db.from("seekmy_reviews").select("*").order("created_at",{ascending:false}).limit(500);if(error)throw new Error(error.message);return reply({reviews:rows.map(review)})}
  if(action==="moderateReview"){await requireAdmin(request,uid);const id=clean(data.id,80),status=data.action==="approve"?"approved":"removed";const{data:row,error}=await db.from("seekmy_reviews").update({status}).eq("id",id).select().single();if(error)throw new Error(error.message);return reply({review:review(row)})}
  if(action==="getAdminActivities"){await requireAdmin(request,uid);const{data:rows,error}=await db.from("seekmy_activities").select("*").order("created_at",{ascending:false}).limit(500);if(error)throw new Error(error.message);return reply({activities:rows.map(activity)})}
  if(action==="moderateActivity"){await requireAdmin(request,uid);const id=clean(data.id,80),nextStatus=data.action==="approve"?"approved":"rejected",reason=nextStatus==="rejected"?(clean(data.reason,500)||"Does not meet activity log guidelines"):"";const{data:row,error}=await db.from("seekmy_activities").update({status:nextStatus,rejection_reason:reason,reviewed_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw new Error(error.message);return reply({activity:activity(row),...await sync(db,row.firebase_uid,row.user_name||"Explorer")})}
  if(action==="adminDeleteUserData"){await requireAdmin(request,uid);const targetUid=clean(data.uid,128);if(!targetUid)return reply({error:"User ID is required."},400);if(targetUid===uid)return reply({error:"Admins cannot delete their own account here."},400);const[{error:a},{error:b},{error:c},{error:d}]=await Promise.all([db.from("seekmy_activities").delete().eq("firebase_uid",targetUid),db.from("seekmy_badges").delete().eq("firebase_uid",targetUid),db.from("seekmy_user_stats").delete().eq("firebase_uid",targetUid),db.from("seekmy_reviews").update({status:"removed",user_name:"Deleted user",comment:"[deleted]",photo_url:"",updated_at:new Date().toISOString()}).eq("firebase_uid",targetUid)]);if(a||b||c||d)throw new Error(a?.message||b?.message||c?.message||d?.message);return reply({success:true})}
  if(action==="signContributorDocument"){await requireAdmin(request,uid);const uri=clean(data.uri,1000),prefix="supabase://contributor-documents/";if(!uri.startsWith(prefix))return reply({error:"Invalid contributor document path."},400);const{data:signed,error}=await db.storage.from("contributor-documents").createSignedUrl(uri.slice(prefix.length),300);if(error)throw new Error(error.message);return reply({url:signed.signedUrl})}
  if(action==="getMyData"){const[{data:a,error:ae},{data:b,error:be}]=await Promise.all([db.from("seekmy_activities").select("*").eq("firebase_uid",uid).order("activity_date",{ascending:false}),db.from("seekmy_badges").select("*").eq("firebase_uid",uid).order("earned_at",{ascending:false})]);if(ae||be)throw new Error(ae?.message||be?.message);return reply({activities:a.map(activity),badges:b.map((x:any)=>({id:`${uid}_${x.badge_key}`,key:x.badge_key,name:x.name,desc:x.description,icon:x.icon,progress:Number(x.progress),created_date:x.earned_at}))})}
  if(action==="createActivity"){const id=clean(data.locationId,128),loc=(await location(id))||fallbackLocation(data,id),km=Number(data.distance),date=clean(data.date,10),photoUrl=clean(data.photoUrl,1000);if(!loc)return reply({error:"Location not found. Please choose a location from the list again."},404);if(!photoUrl)return reply({error:"Upload at least one activity photo before submitting your log for admin review."},400);if(!Number.isFinite(km)||km<=0||km>1000)return reply({error:"Distance must be between 0 and 1,000 km."},400);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(`${date}T00:00:00Z`)>new Date())return reply({error:"Enter a valid activity date that is not in the future."},400);const{data:row,error}=await db.from("seekmy_activities").insert({firebase_uid:uid,user_name:name,location_id:id,location_name:loc.name,state:loc.state||"",activity:loc.activity||"",is_hidden_gem:loc.is_hidden_gem===true,distance_km:Math.round(km*100)/100,duration:clean(data.duration,80),activity_date:date,notes:clean(data.notes),comment:clean(data.comment),photo_url:photoUrl,status:"pending",rejection_reason:""}).select().single();if(error)throw new Error(error.message);return reply({activity:activity(row),newBadges:[],stats:null})}
  if(action==="updateActivity"){const logId=clean(data.id,80),id=clean(data.locationId,128),loc=(await location(id))||fallbackLocation(data,id),km=Number(data.distance),date=clean(data.date,10),photoUrl=clean(data.photoUrl,1000);if(!loc)return reply({error:"Location not found. Please choose a location from the list again."},404);if(!photoUrl)return reply({error:"Upload at least one activity photo before submitting your log for admin review."},400);if(!Number.isFinite(km)||km<=0||km>1000)return reply({error:"Distance must be between 0 and 1,000 km."},400);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(`${date}T00:00:00Z`)>new Date())return reply({error:"Enter a valid activity date that is not in the future."},400);const{data:row,error}=await db.from("seekmy_activities").update({location_id:id,location_name:loc.name,state:loc.state||"",activity:loc.activity||"",is_hidden_gem:loc.is_hidden_gem===true,distance_km:Math.round(km*100)/100,duration:clean(data.duration,80),activity_date:date,notes:clean(data.notes),comment:clean(data.comment),photo_url:photoUrl,status:"pending",rejection_reason:"",reviewed_at:null}).eq("id",logId).eq("firebase_uid",uid).select().single();if(error)throw new Error(error.message);return reply({activity:activity(row),...await sync(db,uid,name)})}
  if(action==="deleteActivity"){const id=clean(data.id,80),{data:row,error:readError}=await db.from("seekmy_activities").select("id,photo_url").eq("id",id).eq("firebase_uid",uid).single();if(readError)return reply({error:"Activity not found."},404);const{error}=await db.from("seekmy_activities").delete().eq("id",id).eq("firebase_uid",uid);if(error)throw new Error(error.message);const marker="/storage/v1/object/public/seekmy-photos/",index=String(row.photo_url||"").indexOf(marker);if(index>=0){const path=decodeURIComponent(String(row.photo_url).slice(index+marker.length));await db.storage.from("seekmy-photos").remove([path])}return reply({success:true,...await sync(db,uid,name)})}
  if(action==="submitReview"){const id=clean(data.locationId,128),loc=(await location(id))||fallbackLocation(data,id),rating=Number(data.rating),comment=reviewComment(data.comment),photoUrl=clean(data.photoUrl,1000);if(!loc)return reply({error:"Location not found. Please open the location again and retry."},404);if(!Number.isInteger(rating)||rating<1||rating>5||!comment)return reply({error:"A rating from 1 to 5 and review comment are required."},400);if(countWords(comment)>MAX_REVIEW_WORDS)return reply({error:`Review comments are limited to ${MAX_REVIEW_WORDS} words.`},400);const{count}=await db.from("seekmy_activities").select("id",{count:"exact",head:true}).eq("firebase_uid",uid).eq("location_id",id).eq("status","approved");if(!count)return reply({error:"Your activity at this location must be approved by admin before you can review it."},409);const{data:row,error}=await db.from("seekmy_reviews").insert({firebase_uid:uid,location_id:id,location_name:loc.name,user_name:name,rating,comment,photo_url:photoUrl}).select().single();if(error?.code==="23505")return reply({error:"You have already reviewed this location."},409);if(error)throw new Error(error.message);return reply({review:review(row),newBadges:(await sync(db,uid,name)).newBadges})}
  if(action==="updateReview"){const id=clean(data.id,80),rating=Number(data.rating),comment=reviewComment(data.comment),photoUrl=clean(data.photoUrl,1000);if(!Number.isInteger(rating)||rating<1||rating>5||!comment)return reply({error:"A rating from 1 to 5 and review comment are required."},400);if(countWords(comment)>MAX_REVIEW_WORDS)return reply({error:`Review comments are limited to ${MAX_REVIEW_WORDS} words.`},400);const{data:existing,error:readError}=await db.from("seekmy_reviews").select("*").eq("id",id).eq("firebase_uid",uid).single();if(readError)return reply({error:"Review not found."},404);if(!withinReviewEditWindow(existing))return reply({error:"Reviews can only be edited within 24 hours after submission."},403);if(existing.status==="removed"||existing.status==="rejected")return reply({error:"This review can no longer be edited."},409);const patch:any={rating,comment,status:"approved",flag_reason:null,updated_at:new Date().toISOString()};if("photoUrl"in data)patch.photo_url=photoUrl;const{data:row,error}=await db.from("seekmy_reviews").update(patch).eq("id",id).eq("firebase_uid",uid).select().single();if(error)throw new Error(error.message);return reply({review:review(row)})}
  if(action==="deleteReview"){const id=clean(data.id,80),{data:existing,error:readError}=await db.from("seekmy_reviews").select("*").eq("id",id).eq("firebase_uid",uid).single();if(readError)return reply({error:"Review not found."},404);if(!withinReviewEditWindow(existing))return reply({error:"Reviews can only be deleted within 24 hours after submission."},403);if(existing.status==="removed"||existing.status==="rejected")return reply({error:"This review has already been removed."},409);const{error}=await db.from("seekmy_reviews").update({status:"removed",updated_at:new Date().toISOString()}).eq("id",id).eq("firebase_uid",uid);if(error)throw new Error(error.message);return reply({success:true,...await sync(db,uid,name)})}
  if(action==="reportReview"){const id=clean(data.id,80),{data:row,error:a}=await db.from("seekmy_reviews").select("flagged_by").eq("id",id).single();if(a)throw new Error(a.message);const flags=row.flagged_by||[];if(flags.includes(uid))return reply({error:"You have already reported this review."},409);const{error}=await db.from("seekmy_reviews").update({status:"flagged",flag_reason:clean(data.reason,200),flagged_by:[...flags,uid]}).eq("id",id);if(error)throw new Error(error.message);return reply({success:true})}
  return reply({error:"Unknown backend action."},404)
}catch(error){console.error(error);const status=Number((error as any)?.status);return reply({error:error instanceof Error?error.message:"Backend request failed."},Number.isInteger(status)&&status>=400&&status<600?status:500)}});
