import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const BADGES=[
  {key:"first-footstep",icon:"🥾",name:"First Footstep",desc:"Log your first outdoor activity",requirement:1,metric:"activities"},{key:"state-explorer",icon:"🧭",name:"State Explorer",desc:"Visit 3 different Malaysian states",requirement:3,metric:"states"},{key:"malaysia-wanderer",icon:"🗺️",name:"Malaysia Wanderer",desc:"Visit 5 different Malaysian states",requirement:5,metric:"states"},{key:"hidden-gem-hunter",icon:"💎",name:"Hidden Gem Hunter",desc:"Visit 3 hidden-gem locations",requirement:3,metric:"gems"},{key:"first-contribution",icon:"✍️",name:"First Contribution",desc:"Write your first community review",requirement:1,metric:"reviews"},{key:"local-storyteller",icon:"📖",name:"Local Storyteller",desc:"Write 3 community reviews",requirement:3,metric:"reviews"},{key:"trusted-contributor",icon:"✅",name:"Trusted Contributor",desc:"Write 5 community reviews",requirement:5,metric:"reviews"},{key:"community-favourite",icon:"⭐",name:"Community Favourite",desc:"Write 10 community reviews",requirement:10,metric:"reviews"},{key:"malaysia-insider",icon:"🏆",name:"Malaysia Insider",desc:"Log 100 km of outdoor activities",requirement:100,metric:"km"},
];
function reply(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json"}})}
function clean(value:unknown,max=2000){return String(value??"").trim().slice(0,max)}
async function verifyUser(request:Request){const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)throw new Error("Please sign in first.");const key=Deno.env.get("FIREBASE_WEB_API_KEY");if(!key)throw new Error("Firebase authentication is not configured.");const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${key}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken:token})});if(!r.ok)throw new Error("Your login session is invalid or expired.");const user=(await r.json()).users?.[0];if(!user?.localId)throw new Error("Firebase user not found.");return user}
async function requireAdmin(request:Request,uid:string){const project=clean(Deno.env.get("FIREBASE_PROJECT_ID"),100),token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const r=await fetch(`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(project)}/databases/(default)/documents/User/${encodeURIComponent(uid)}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error("Unable to verify administrator access.");const profile=await r.json();if(fromFs(profile.fields?.role)!=="admin")throw new Error("Administrator access is required.")}
function fromFs(v:any):any{if(!v)return null;if("nullValue"in v)return null;if("stringValue"in v)return v.stringValue;if("integerValue"in v)return Number(v.integerValue);if("doubleValue"in v)return Number(v.doubleValue);if("booleanValue"in v)return v.booleanValue;if("arrayValue"in v)return(v.arrayValue.values||[]).map(fromFs);if("mapValue"in v)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,fromFs(x)]));return null}
async function location(id:string){const project=clean(Deno.env.get("FIREBASE_PROJECT_ID"),100);if(!project)throw new Error("Firebase project ID is not configured.");const r=await fetch(`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(project)}/databases/(default)/documents/Location/${encodeURIComponent(id)}`);if(r.status===404)return null;if(!r.ok)throw new Error("Unable to verify the selected location.");const d=await r.json();return{id,...Object.fromEntries(Object.entries(d.fields||{}).map(([k,v])=>[k,fromFs(v)]))}}
function backendDb(){
  const url=Deno.env.get("SUPABASE_URL");
  const serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if(!url||!serviceRoleKey)throw new Error("Supabase service role is not configured. Add SUPABASE_SERVICE_ROLE_KEY to Edge Function secrets.");
  return createClient(url,serviceRoleKey,{auth:{persistSession:false},global:{headers:{Authorization:`Bearer ${serviceRoleKey}`}}});
}
function activity(row:any){return{id:row.id,locationId:row.location_id,location:row.location_name,state:row.state,activity:row.activity,distance:Number(row.distance_km),duration:row.duration,date:row.activity_date,notes:row.notes,comment:row.comment,photoUrl:row.photo_url,created_date:row.created_at}}
function review(row:any){return{id:row.id,locationId:row.location_id,locationName:row.location_name,userId:row.firebase_uid,userName:row.user_name,rating:row.rating,comment:row.comment,status:row.status,flagReason:row.flag_reason,flaggedBy:row.flagged_by||[],date:new Date(row.created_at).toLocaleDateString("en-MY",{month:"short",year:"numeric",timeZone:"Asia/Kuala_Lumpur"}),created_date:row.created_at,updated_date:row.updated_at}}
function withinReviewEditWindow(row:any){return Date.now()-new Date(row.created_at).getTime()<=24*60*60*1000}
async function sync(db:any,uid:string,name:string){const[{data:logs,error:a},{data:reviews,error:b},{data:old,error:c}]=await Promise.all([db.from("seekmy_activities").select("activity,state,distance_km,is_hidden_gem").eq("firebase_uid",uid),db.from("seekmy_reviews").select("id").eq("firebase_uid",uid).not("status","in",'(removed,rejected)'),db.from("seekmy_badges").select("badge_key").eq("firebase_uid",uid)]);if(a||b||c)throw new Error(a?.message||b?.message||c?.message);const m:any={activities:logs.length,hikes:logs.filter((x:any)=>/hike/i.test(x.activity)).length,dives:logs.filter((x:any)=>/div/i.test(x.activity)).length,states:new Set(logs.map((x:any)=>x.state).filter(Boolean)).size,km:logs.reduce((s:number,x:any)=>s+Number(x.distance_km||0),0),gems:logs.filter((x:any)=>x.is_hidden_gem).length,reviews:reviews.length,cycleKm:logs.filter((x:any)=>/cycl/i.test(x.activity)).reduce((s:number,x:any)=>s+Number(x.distance_km||0),0),camps:logs.filter((x:any)=>/camp/i.test(x.activity)).length};const earned=BADGES.filter((x:any)=>m[x.metric]>=x.requirement),earnedKeys=new Set(earned.map(x=>x.key)),keys=new Set(old.map((x:any)=>x.badge_key)),fresh=earned.filter(x=>!keys.has(x.key)),revoked=old.filter((x:any)=>!earnedKeys.has(x.badge_key)).map((x:any)=>x.badge_key);if(fresh.length){const{error}=await db.from("seekmy_badges").upsert(fresh.map(x=>({firebase_uid:uid,badge_key:x.key,name:x.name,description:x.desc,icon:x.icon,progress:m[x.metric]})));if(error)throw new Error(error.message)}if(revoked.length){const{error}=await db.from("seekmy_badges").delete().eq("firebase_uid",uid).in("badge_key",revoked);if(error)throw new Error(error.message)}const stats={total_km:Math.round(m.km*100)/100,checkins:logs.length,states:m.states};const{error}=await db.from("seekmy_user_stats").upsert({firebase_uid:uid,display_name:name,...stats,updated_at:new Date().toISOString()});if(error)throw new Error(error.message);return{stats,newBadges:fresh,revokedBadges:revoked}}

Deno.serve(async request=>{if(request.method==="OPTIONS")return new Response("ok",{headers:CORS});if(request.method!=="POST")return reply({error:"Method not allowed."},405);try{const body=await request.json(),action=clean(body.action,40),data=body.payload||{};
  if(action==="getWeather"){const key=Deno.env.get("OPENWEATHER_API_KEY");if(!key)return reply({error:"Weather is not configured."},503);const p=new URLSearchParams({appid:key,units:"metric"}),lat=Number(data.lat),lng=Number(data.lng),hasCoords=Number.isFinite(lat)&&Number.isFinite(lng);if(hasCoords){p.set("lat",String(lat));p.set("lon",String(lng))}else p.set("q",`${clean(data.locationName||data.state,120)||"Kuala Lumpur"},MY`);const[a,b,c]=await Promise.all([fetch(`https://api.openweathermap.org/data/2.5/weather?${p}`),fetch(`https://api.openweathermap.org/data/2.5/forecast?${p}`),hasCoords?fetch(`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(String(lat))}&longitude=${encodeURIComponent(String(lng))}&hourly=uv_index&forecast_days=1&timezone=Asia%2FKuala_Lumpur`).catch(()=>null):Promise.resolve(null)]);if(!a.ok||!b.ok)return reply({error:"Weather data is unavailable."},503);const uvJson=c?.ok?await c.json().catch(()=>null):null,times=Array.isArray(uvJson?.hourly?.time)?uvJson.hourly.time:[],values=Array.isArray(uvJson?.hourly?.uv_index)?uvJson.hourly.uv_index.map(Number):[],now=Date.now(),idx=times.reduce((best:number,time:string,index:number)=>{const d=Math.abs(new Date(`${time}:00+08:00`).getTime()-now),bd=best>=0?Math.abs(new Date(`${times[best]}:00+08:00`).getTime()-now):Number.POSITIVE_INFINITY;return d<bd?index:best},-1),raw=idx>=0?values[idx]:NaN,uv=Number.isFinite(raw)?Math.round(raw*10)/10:null;return reply({current:await a.json(),forecast:await b.json(),uv:{value:uv}})}
  const db=backendDb();
  if(action==="getReviews"){const{data:rows,error}=await db.from("seekmy_reviews").select("*").eq("location_id",clean(data.locationId,128)).eq("status","approved").order("created_at",{ascending:false});if(error)throw new Error(error.message);return reply({reviews:rows.map(review)})}
  if(action==="getLocationReviewSummaries"){const{data:rows,error}=await db.from("seekmy_reviews").select("location_id,location_name,rating").eq("status","approved");if(error)throw new Error(error.message);const grouped=new Map();for(const row of rows||[]){const key=String(row.location_id),current=grouped.get(key)||{locationId:key,locationName:row.location_name||"",count:0,total:0};current.count+=1;current.total+=Number(row.rating||0);if(row.location_name)current.locationName=row.location_name;grouped.set(key,current)}return reply({summaries:[...grouped.values()].map(x=>({locationId:x.locationId,locationName:x.locationName,count:x.count,rating:Math.round((x.total/x.count)*10)/10}))})}
  if(action==="getLeaderboard"){const period=data.period==="monthly"?"monthly":"weekly",start=new Date();period==="weekly"?start.setUTCDate(start.getUTCDate()-7):start.setUTCMonth(start.getUTCMonth()-1);const[{data:logs,error:a},{data:stats,error:b}]=await Promise.all([db.from("seekmy_activities").select("firebase_uid,state,distance_km").gte("activity_date",start.toISOString().slice(0,10)),db.from("seekmy_user_stats").select("firebase_uid,display_name")]);if(a||b)throw new Error(a?.message||b?.message);const names=new Map((stats||[]).map((x:any)=>[x.firebase_uid,x.display_name])),totals=new Map();for(const x of logs||[]){const row=totals.get(x.firebase_uid)||{id:x.firebase_uid,name:names.get(x.firebase_uid)||"Explorer",km:0,checkins:0,stateSet:new Set()};row.km+=Number(x.distance_km||0);row.checkins++;if(x.state)row.stateSet.add(x.state);totals.set(x.firebase_uid,row)}return reply({entries:[...totals.values()].map(x=>({id:x.id,name:x.name,km:Math.round(x.km*100)/100,checkins:x.checkins,states:x.stateSet.size})),badges:BADGES})}
  const user=await verifyUser(request),uid=user.localId,name=user.displayName||user.email?.split("@")[0]||"Explorer";
  if(action==="getAdminReviews"){await requireAdmin(request,uid);const{data:rows,error}=await db.from("seekmy_reviews").select("*").order("created_at",{ascending:false}).limit(500);if(error)throw new Error(error.message);return reply({reviews:rows.map(review)})}
  if(action==="moderateReview"){await requireAdmin(request,uid);const id=clean(data.id,80),status=data.action==="approve"?"approved":"removed";const{data:row,error}=await db.from("seekmy_reviews").update({status}).eq("id",id).select().single();if(error)throw new Error(error.message);return reply({review:review(row)})}
  if(action==="signContributorDocument"){await requireAdmin(request,uid);const uri=clean(data.uri,1000),prefix="supabase://contributor-documents/";if(!uri.startsWith(prefix))return reply({error:"Invalid contributor document path."},400);const{data:signed,error}=await db.storage.from("contributor-documents").createSignedUrl(uri.slice(prefix.length),300);if(error)throw new Error(error.message);return reply({url:signed.signedUrl})}
  if(action==="getMyData"){const[{data:a,error:ae},{data:b,error:be}]=await Promise.all([db.from("seekmy_activities").select("*").eq("firebase_uid",uid).order("activity_date",{ascending:false}),db.from("seekmy_badges").select("*").eq("firebase_uid",uid).order("earned_at",{ascending:false})]);if(ae||be)throw new Error(ae?.message||be?.message);return reply({activities:a.map(activity),badges:b.map((x:any)=>({id:`${uid}_${x.badge_key}`,key:x.badge_key,name:x.name,desc:x.description,icon:x.icon,progress:Number(x.progress),created_date:x.earned_at}))})}
  if(action==="createActivity"){const id=clean(data.locationId,128),loc=await location(id),km=Number(data.distance),date=clean(data.date,10);if(!loc)return reply({error:"Location not found."},404);if(!Number.isFinite(km)||km<=0||km>1000)return reply({error:"Distance must be between 0 and 1,000 km."},400);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(`${date}T00:00:00Z`)>new Date())return reply({error:"Enter a valid activity date that is not in the future."},400);const{data:row,error}=await db.from("seekmy_activities").insert({firebase_uid:uid,location_id:id,location_name:loc.name,state:loc.state||"",activity:loc.activity||"",is_hidden_gem:loc.is_hidden_gem===true,distance_km:Math.round(km*100)/100,duration:clean(data.duration,80),activity_date:date,notes:clean(data.notes),comment:clean(data.comment),photo_url:clean(data.photoUrl)}).select().single();if(error)throw new Error(error.message);return reply({activity:activity(row),...await sync(db,uid,name)})}
  if(action==="deleteActivity"){const id=clean(data.id,80),{data:row,error:readError}=await db.from("seekmy_activities").select("id,photo_url").eq("id",id).eq("firebase_uid",uid).single();if(readError)return reply({error:"Activity not found."},404);const{error}=await db.from("seekmy_activities").delete().eq("id",id).eq("firebase_uid",uid);if(error)throw new Error(error.message);const marker="/storage/v1/object/public/seekmy-photos/",index=String(row.photo_url||"").indexOf(marker);if(index>=0){const path=decodeURIComponent(String(row.photo_url).slice(index+marker.length));await db.storage.from("seekmy-photos").remove([path])}return reply({success:true,...await sync(db,uid,name)})}
  if(action==="submitReview"){const id=clean(data.locationId,128),loc=await location(id),rating=Number(data.rating),comment=clean(data.comment);if(!loc)return reply({error:"Location not found."},404);if(!Number.isInteger(rating)||rating<1||rating>5||!comment)return reply({error:"A rating from 1 to 5 and review comment are required."},400);const{count}=await db.from("seekmy_activities").select("id",{count:"exact",head:true}).eq("firebase_uid",uid).eq("location_id",id);if(!count)return reply({error:"Log an activity at this location before reviewing it."},409);const{data:row,error}=await db.from("seekmy_reviews").insert({firebase_uid:uid,location_id:id,location_name:loc.name,user_name:name,rating,comment}).select().single();if(error?.code==="23505")return reply({error:"You have already reviewed this location."},409);if(error)throw new Error(error.message);return reply({review:review(row),newBadges:(await sync(db,uid,name)).newBadges})}
  if(action==="updateReview"){const id=clean(data.id,80),rating=Number(data.rating),comment=clean(data.comment);if(!Number.isInteger(rating)||rating<1||rating>5||!comment)return reply({error:"A rating from 1 to 5 and review comment are required."},400);const{data:existing,error:readError}=await db.from("seekmy_reviews").select("*").eq("id",id).eq("firebase_uid",uid).single();if(readError)return reply({error:"Review not found."},404);if(!withinReviewEditWindow(existing))return reply({error:"Reviews can only be edited within 24 hours after submission."},403);if(existing.status==="removed"||existing.status==="rejected")return reply({error:"This review can no longer be edited."},409);const{data:row,error}=await db.from("seekmy_reviews").update({rating,comment,status:"approved",flag_reason:null,updated_at:new Date().toISOString()}).eq("id",id).eq("firebase_uid",uid).select().single();if(error)throw new Error(error.message);return reply({review:review(row)})}
  if(action==="deleteReview"){const id=clean(data.id,80),{data:existing,error:readError}=await db.from("seekmy_reviews").select("*").eq("id",id).eq("firebase_uid",uid).single();if(readError)return reply({error:"Review not found."},404);if(!withinReviewEditWindow(existing))return reply({error:"Reviews can only be deleted within 24 hours after submission."},403);if(existing.status==="removed"||existing.status==="rejected")return reply({error:"This review has already been removed."},409);const{error}=await db.from("seekmy_reviews").update({status:"removed",updated_at:new Date().toISOString()}).eq("id",id).eq("firebase_uid",uid);if(error)throw new Error(error.message);return reply({success:true,...await sync(db,uid,name)})}
  if(action==="reportReview"){const id=clean(data.id,80),{data:row,error:a}=await db.from("seekmy_reviews").select("flagged_by").eq("id",id).single();if(a)throw new Error(a.message);const flags=row.flagged_by||[];if(flags.includes(uid))return reply({error:"You have already reported this review."},409);const{error}=await db.from("seekmy_reviews").update({status:"flagged",flag_reason:clean(data.reason,200),flagged_by:[...flags,uid]}).eq("id",id);if(error)throw new Error(error.message);return reply({success:true})}
  return reply({error:"Unknown backend action."},404)
}catch(error){console.error(error);return reply({error:error instanceof Error?error.message:"Backend request failed."},500)}});
