import type { Location } from "../lib/types";
import { C } from "../lib/tokens";

export const PENINSULAR = [
  {code:"JHR",name:"Johor"},{code:"KDH",name:"Kedah"},{code:"KTN",name:"Kelantan"},
  {code:"MLK",name:"Melaka"},{code:"NSN",name:"Negeri Sembilan"},{code:"PHG",name:"Pahang"},
  {code:"PRK",name:"Perak"},{code:"PLS",name:"Perlis"},{code:"SLG",name:"Selangor"},
  {code:"TRG",name:"Terengganu"},{code:"PNG",name:"Pulau Pinang"},
];
export const EAST = [{code:"SBH",name:"Sabah"},{code:"SWK",name:"Sarawak"}];
export const FED  = [{code:"KL",name:"Kuala Lumpur"},{code:"LBN",name:"Labuan"},{code:"PTJ",name:"Putrajaya"}];
export const ALL_STATES = [
  ...PENINSULAR.map(s=>({...s,region:"Peninsular Malaysia"})),
  ...EAST.map(s=>({...s,region:"East Malaysia"})),
  ...FED.map(s=>({...s,region:"Federal Territory"})),
];

export const HIDDEN_GEMS = [
  {id:1,locationId:10,name:"Fairy Cave & Wind Cave",state:"Sarawak",desc:"Stunning limestone cavern with natural skylights illuminating cathedral-like formations. Adjacent Wind Cave features narrow passages and cool air currents.",grad:`linear-gradient(135deg, ${C.sunset} 0%, #c2410c 100%)`},
  {id:2,locationId:47,name:"Tasik Cermin",state:"Terengganu",desc:"Crystal-clear freshwater lake hidden inside a limestone cave. The mirrored surface reflects the cave ceiling, creating an ethereal double landscape.",grad:`linear-gradient(135deg, #38bdf8 0%, #0369a1 100%)`},
  {id:3,locationId:41,name:"Gunung Stong Waterfall",state:"Kelantan",desc:"Malaysia's highest waterfall cascades 305m through ancient primary rainforest inside Stong State Park. Rarely visited, true wilderness solitude.",grad:`linear-gradient(135deg, ${C.forest} 0%, ${C.jungle} 100%)`},
];

export const ACTIVITY_FILTERS = [
  {id:"all",label:"All",icon:"🌿"},{id:"Hiking",label:"Hiking",icon:"🥾"},
  {id:"Trail Running",label:"Trail Running",icon:"🏃"},{id:"Jogging",label:"Jogging",icon:"👟"},
  {id:"Cycling",label:"Cycling",icon:"🚴"},{id:"Swimming",label:"Swimming",icon:"🏊"},
  {id:"Diving",label:"Diving",icon:"🤿"},{id:"Rock Climbing",label:"Rock Climbing",icon:"🧗"},
  {id:"Water Sports",label:"Water Sports",icon:"🚣"},{id:"Camping",label:"Camping",icon:"⛺"},
];

export const PRESET_FILTERS = [
  {id:"Family Friendly",label:"Family Friendly",icon:"👨‍👩‍👧"},
  {id:"Beginner",label:"Beginner",icon:"🌱"},
  {id:"Advanced",label:"Advanced",icon:"⚡"},
  {id:"Pet Friendly",label:"Pet Friendly",icon:"🐾"},
];

export const LOCATIONS: Location[] = [
  // ── Sabah ──
  {id:1,name:"Kinabalu Summit Trail",state:"Sabah",stateCode:"SBH",activity:"Hiking",difficulty:"Hard",distance:"8.7 km",duration:"10–12 hrs",rating:4.9,reviews:312,badge:"Legend",weather:"Partly Cloudy",temp:15,humidity:85,wind:12,color:C.jungle,emoji:"⛰️",description:"The highest peak in Malaysia at 4,095m — a life-defining ascent above the clouds.",facilities:["Rest stations","Laban Rata hut","Guides required","Toilet facilities"],bestMonths:"March – September",accessibility:"Requires hiking experience and fitness. Permit required.",tags:["Advanced"],budget:"Medium"},
  {id:2,name:"Sipadan Dive Site",state:"Sabah",stateCode:"SBH",activity:"Diving",difficulty:"Moderate",distance:"N/A",duration:"Full Day",rating:5.0,reviews:489,badge:"Top Rated",weather:"Sunny",temp:29,humidity:78,wind:8,color:C.forest,emoji:"🐠",description:"Consistently ranked among the world's top 10 dive sites — vertical walls, sea turtles, reef fish.",facilities:["Dive operators","Equipment rental","Dive guides","Permits required"],bestMonths:"April – December",accessibility:"Open Water certification minimum. Daily permit quota — book early.",tags:["Advanced"],budget:"High"},
  {id:3,name:"Meskah Heritage Trail",state:"Sabah",stateCode:"SBH",activity:"Hiking",difficulty:"Moderate",distance:"6.2 km",duration:"4–5 hrs",rating:4.5,reviews:98,badge:"Cultural Trek",weather:"Cloudy",temp:24,humidity:82,wind:7,color:"#2a5a4a",emoji:"🌿",description:"A cultural trail through Kadazan-Dusun villages and paddy fields with views of Kinabalu's foothills.",facilities:["Village homestay","Guides","Trail markers","Basic facilities"],bestMonths:"March – October",accessibility:"Moderate fitness. Cultural etiquette required.",tags:["Family Friendly"],budget:"Low"},
  {id:4,name:"Sepilok Rainforest Jog",state:"Sabah",stateCode:"SBH",activity:"Jogging",difficulty:"Easy",distance:"4 km",duration:"30–45 mins",rating:4.3,reviews:74,badge:"Jungle Run",weather:"Partly Cloudy",temp:28,humidity:84,wind:5,color:C.forest,emoji:"🦧",description:"Paved and boardwalk jogging path around Sepilok Orangutan Rehabilitation Centre — wildlife sightings guaranteed.",facilities:["Toilets","Parking","Café","Visitor centre"],bestMonths:"Year-round",accessibility:"Fully accessible. Pushchair-friendly on main paths.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:5,name:"Semporna Reef Snorkel",state:"Sabah",stateCode:"SBH",activity:"Swimming",difficulty:"Easy",distance:"N/A",duration:"Half Day",rating:4.7,reviews:211,badge:"Marine Wonder",weather:"Sunny",temp:30,humidity:76,wind:6,color:"#1a6b8a",emoji:"🐟",description:"Turquoise shallow reefs around Mabul Island — abundant reef fish, starfish, and gentle currents.",facilities:["Snorkel gear rental","Boat transfers","Beach shack food","Life jackets"],bestMonths:"April – October",accessibility:"Suitable for non-swimmers with life jacket.",tags:["Family Friendly","Beginner"],budget:"Medium"},
  // ── Sarawak ──
  {id:6,name:"Bako National Park Camp",state:"Sarawak",stateCode:"SWK",activity:"Camping",difficulty:"Easy",distance:"N/A",duration:"Overnight",rating:4.7,reviews:156,badge:"Wildlife Camp",weather:"Partly Cloudy",temp:27,humidity:88,wind:4,color:C.jungle,emoji:"🏕️",description:"Camp within Sarawak's oldest national park — proboscis monkeys, pitcher plants, and dramatic sea stacks.",facilities:["Official campsites","Park accommodation","Guided walks","Canteen"],bestMonths:"March – October",accessibility:"Good for families. Boat access from Kuching.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:7,name:"Damai Beach Bouldering",state:"Sarawak",stateCode:"SWK",activity:"Rock Climbing",difficulty:"Moderate",distance:"N/A",duration:"Half Day",rating:4.4,reviews:67,badge:"Sea Crag",weather:"Sunny",temp:29,humidity:80,wind:7,color:"#8b4513",emoji:"🧗",description:"Sea-cliff bouldering above the South China Sea — sandstone crags with ocean views.",facilities:["Nearby guesthouses","Chalk available","Basic gear rental"],bestMonths:"April – October",accessibility:"Some climbing experience recommended.",tags:["Beginner"],budget:"Low"},
  {id:8,name:"Gunung Santubong Trek",state:"Sarawak",stateCode:"SWK",activity:"Hiking",difficulty:"Hard",distance:"9 km",duration:"7–9 hrs",rating:4.6,reviews:112,badge:"Coastal Summit",weather:"Partly Cloudy",temp:28,humidity:87,wind:9,color:C.jungle,emoji:"⛰️",description:"A strenuous summit hike with dramatic views of the South China Sea from 810m — dense jungle and rocky scrambles.",facilities:["Trailhead signage","Water streams","Ranger station"],bestMonths:"April – September",accessibility:"Experienced hikers only. Very steep in places.",tags:["Advanced"],budget:"Free"},
  {id:9,name:"Kuching Waterfront Cycling",state:"Sarawak",stateCode:"SWK",activity:"Cycling",difficulty:"Easy",distance:"12 km",duration:"1–1.5 hrs",rating:4.2,reviews:88,badge:"City Ride",weather:"Sunny",temp:30,humidity:79,wind:8,color:"#5c4a2a",emoji:"🚴",description:"Flat riverside cycling route along the Sarawak River past colonial shophouses and vibrant street art.",facilities:["Bike rental","Food stalls","Toilets","Shaded areas"],bestMonths:"Year-round",accessibility:"Flat, fully accessible.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Low"},
  {id:10,name:"Mulu Caves Trekking",state:"Sarawak",stateCode:"SWK",activity:"Hiking",difficulty:"Moderate",distance:"14 km",duration:"Full Day",rating:4.8,reviews:203,badge:"World Heritage",weather:"Cloudy",temp:26,humidity:90,wind:3,color:"#3d2c1a",emoji:"🦇",description:"UNESCO World Heritage caves — the world's largest cave chamber (Sarawak Chamber) and millions of bats at sunset.",facilities:["Park lodging","Guided tours required","Boardwalks","Lighting"],bestMonths:"Year-round",accessibility:"Moderate fitness. Some sections require crawling.",tags:["Advanced"],budget:"High"},
  // ── Selangor ──
  {id:11,name:"Broga Hill Trail",state:"Selangor",stateCode:"SLG",activity:"Hiking",difficulty:"Easy",distance:"4.2 km",duration:"2–3 hrs",rating:4.7,reviews:851,badge:"Family Favourite",weather:"Cloudy",temp:27,humidity:80,wind:6,color:C.forest,emoji:"🌄",description:"The most popular sunrise hike in Selangor — gentle climb through rubber estates to open rocky summits.",facilities:["Parking nearby","Food stalls at base","Trail markers"],bestMonths:"Year-round",accessibility:"Beginner-friendly. Suitable for families with older children.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Free"},
  {id:12,name:"FRIM Kepong Trail Run",state:"Selangor",stateCode:"SLG",activity:"Trail Running",difficulty:"Moderate",distance:"10 km",duration:"1.5–2 hrs",rating:4.5,reviews:183,badge:"Forest Run",weather:"Partly Cloudy",temp:28,humidity:82,wind:5,color:"#2a5a4a",emoji:"🏃",description:"Winding single-track trails through the Forest Research Institute Malaysia — canopy walkways and towering dipterocarps.",facilities:["Parking","Canopy walkway","Visitor centre","Toilets"],bestMonths:"Year-round",accessibility:"Moderate fitness required. Trail shoes essential.",tags:["Beginner","Pet Friendly"],budget:"Low"},
  {id:13,name:"Batu Caves Rock Face",state:"Selangor",stateCode:"SLG",activity:"Rock Climbing",difficulty:"Hard",distance:"N/A",duration:"Full Day",rating:4.6,reviews:114,badge:"Limestone Legend",weather:"Partly Cloudy",temp:30,humidity:79,wind:5,color:"#6b3a3a",emoji:"🏛️",description:"Iconic limestone monolith with established bolted sport routes from 5a to 7c+.",facilities:["Gear rental nearby","Guided sessions","Food stalls","Parking"],bestMonths:"March – October",accessibility:"Some routes for beginners with guides.",tags:["Advanced"],budget:"Low"},
  {id:14,name:"Gunung Nuang Summit Run",state:"Selangor",stateCode:"SLG",activity:"Trail Running",difficulty:"Hard",distance:"26 km",duration:"6–9 hrs",rating:4.7,reviews:95,badge:"Ultra Challenge",weather:"Cloudy",temp:22,humidity:88,wind:8,color:C.jungle,emoji:"⛰️",description:"The highest peak in Selangor — a demanding trail run through ancient rainforest to the misty summit.",facilities:["Trail markers","Campsite","River crossings","Basic huts"],bestMonths:"April – October",accessibility:"Experienced trail runners only.",tags:["Advanced"],budget:"Low"},
  {id:15,name:"Subang Alam Cycling Park",state:"Selangor",stateCode:"SLG",activity:"Cycling",difficulty:"Easy",distance:"8 km",duration:"45 mins",rating:4.1,reviews:142,badge:"Urban Ride",weather:"Sunny",temp:32,humidity:72,wind:8,color:"#5c4a2a",emoji:"🚴",description:"Purpose-built cycling park with paved loops, pump track, and skills area — great for all levels.",facilities:["Bike rental","Pump track","Toilets","Parking","Shaded rest areas"],bestMonths:"Year-round",accessibility:"Fully accessible. Bike rental on-site.",tags:["Family Friendly","Beginner"],budget:"Free"},
  // ── Pahang ──
  {id:16,name:"Taman Negara Wild Camp",state:"Pahang",stateCode:"PHG",activity:"Camping",difficulty:"Hard",distance:"N/A",duration:"Multi-Day",rating:4.8,reviews:73,badge:"Primal Jungle",weather:"Cloudy",temp:25,humidity:92,wind:3,color:C.jungle,emoji:"🌴",description:"Deep jungle camping in one of the world's oldest rainforests — orang asli guides, remote river camps.",facilities:["Guide required","Camping equipment available","River boats","Ranger station"],bestMonths:"March – October",accessibility:"Requires advance booking and guide.",tags:["Advanced"],budget:"Medium"},
  {id:17,name:"Tioman Coral Garden",state:"Pahang",stateCode:"PHG",activity:"Diving",difficulty:"Easy",distance:"N/A",duration:"Half Day",rating:4.6,reviews:201,badge:"Best Value",weather:"Sunny",temp:28,humidity:76,wind:7,color:C.forest,emoji:"🐡",description:"Shallow coral formations with abundant marine life just metres from the beach.",facilities:["Multiple dive operators","Equipment rental","Snorkeling","Beach accommodation"],bestMonths:"March – October",accessibility:"Beginner-friendly.",tags:["Family Friendly","Beginner"],budget:"Medium"},
  {id:18,name:"Cherating Water Sports",state:"Pahang",stateCode:"PHG",activity:"Water Sports",difficulty:"Easy",distance:"N/A",duration:"Half Day",rating:4.3,reviews:198,badge:"Beach Fun",weather:"Sunny",temp:30,humidity:74,wind:8,color:"#1a6b8a",emoji:"🚣",description:"Calm coastal waters for kayaking, stand-up paddleboarding, and banana boat rides.",facilities:["Equipment rental","Safety instructors","Toilets","Food stalls"],bestMonths:"March – September",accessibility:"All skill levels. Life jackets provided.",tags:["Family Friendly","Beginner"],budget:"Medium"},
  {id:19,name:"Endau-Rompin Trek",state:"Pahang",stateCode:"PHG",activity:"Camping",difficulty:"Moderate",distance:"25 km",duration:"3 Days",rating:4.7,reviews:89,badge:"Wild Escape",weather:"Partly Cloudy",temp:26,humidity:90,wind:4,color:C.jungle,emoji:"🏕️",description:"One of Malaysia's oldest national parks — a 3-day jungle expedition through primary rainforest.",facilities:["Campsite platforms","Guides required","River crossings","Ranger station"],bestMonths:"March – October",accessibility:"Requires guide. Multi-day commitment.",tags:["Advanced"],budget:"Medium"},
  {id:20,name:"Genting Highlands Hike",state:"Pahang",stateCode:"PHG",activity:"Hiking",difficulty:"Moderate",distance:"7 km",duration:"3–4 hrs",rating:4.3,reviews:167,badge:"Cloud Walk",weather:"Cloudy",temp:18,humidity:90,wind:15,color:"#2a5a4a",emoji:"☁️",description:"Forest trail ascending to Genting's highland plateau — mist-shrouded jungle and cool highland air.",facilities:["Cable car alternative","Marked trail","Parking","Cafés at summit"],bestMonths:"Year-round",accessibility:"Moderate fitness. Can descend by cable car.",tags:["Family Friendly"],budget:"Low"},
  // ── Perak ──
  {id:21,name:"Titiwangsa Highland Cycling",state:"Perak",stateCode:"PRK",activity:"Cycling",difficulty:"Hard",distance:"62 km",duration:"5–7 hrs",rating:4.4,reviews:78,badge:"Epic Route",weather:"Partly Cloudy",temp:22,humidity:80,wind:14,color:C.jungle,emoji:"🏔️",description:"Mountain road cycling through the Titiwangsa range — tea plantations and highland resorts.",facilities:["Pit stops in Cameron Highlands","Basic repair shops","Accommodation"],bestMonths:"April – September",accessibility:"Road cycling experience required.",tags:["Advanced"],budget:"Low"},
  {id:22,name:"Royal Belum Rainforest Trek",state:"Perak",stateCode:"PRK",activity:"Hiking",difficulty:"Moderate",distance:"10 km",duration:"Full Day",rating:4.7,reviews:134,badge:"Rare Wildlife",weather:"Cloudy",temp:26,humidity:88,wind:5,color:C.jungle,emoji:"🐘",description:"One of the world's oldest rainforests — home to Rafflesia, Sumatran elephants, and rare Malayan tigers.",facilities:["Boat access","Guided tours mandatory","Eco-lodge","Photography hides"],bestMonths:"March – October",accessibility:"Guide required. Boat transfers included.",tags:["Advanced"],budget:"High"},
  {id:23,name:"Ipoh Mural Heritage Jog",state:"Perak",stateCode:"PRK",activity:"Jogging",difficulty:"Easy",distance:"4 km",duration:"35–45 mins",rating:4.2,reviews:211,badge:"Art Run",weather:"Sunny",temp:32,humidity:74,wind:7,color:"#5c4a2a",emoji:"🎨",description:"Urban jogging route through Ipoh's colonial old town past famous 3D murals and heritage kopitiam.",facilities:["Toilets in cafés","Water fountains","Shaded lanes","Parking nearby"],bestMonths:"Year-round",accessibility:"Flat, fully accessible.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Free"},
  {id:24,name:"Pangkor Island Snorkel",state:"Perak",stateCode:"PRK",activity:"Swimming",difficulty:"Easy",distance:"N/A",duration:"Half Day",rating:4.4,reviews:155,badge:"Island Escape",weather:"Sunny",temp:29,humidity:77,wind:7,color:"#1a6b8a",emoji:"🏖️",description:"Crystal clear waters around Pulau Pangkor Laut — vibrant reef fish and calm sheltered coves.",facilities:["Resort facilities","Snorkel gear rental","Beach chairs","Boat transfers"],bestMonths:"November – April",accessibility:"Beginner-friendly. Life jackets available.",tags:["Family Friendly","Beginner"],budget:"Medium"},
  {id:25,name:"Gunung Korbu Trek",state:"Perak",stateCode:"PRK",activity:"Hiking",difficulty:"Hard",distance:"14 km",duration:"10–12 hrs",rating:4.5,reviews:61,badge:"Jungle Summit",weather:"Partly Cloudy",temp:20,humidity:87,wind:10,color:C.jungle,emoji:"⛰️",description:"The second highest peak in Peninsular Malaysia at 2,183m — a serious multi-day jungle expedition.",facilities:["Camp sites","Water streams","Guide required","Permit needed"],bestMonths:"May – September",accessibility:"Experienced mountaineers only.",tags:["Advanced"],budget:"Low"},
  // ── Pulau Pinang ──
  {id:26,name:"Penang Hill Forest Trail",state:"Pulau Pinang",stateCode:"PNG",activity:"Hiking",difficulty:"Moderate",distance:"5.8 km",duration:"4–5 hrs",rating:4.5,reviews:298,badge:"Heritage Hike",weather:"Cloudy",temp:23,humidity:86,wind:11,color:"#2a5a4a",emoji:"🌳",description:"The Moon Gate Heritage Trail through colonial-era forest reserve with century-old bungalows.",facilities:["Funicular alternative","Visitor centre","Café at summit","Trail maps"],bestMonths:"October – April",accessibility:"Moderate. Can take funicular down if needed.",tags:["Family Friendly"],budget:"Low"},
  {id:27,name:"Penang Botanic Garden Jog",state:"Pulau Pinang",stateCode:"PNG",activity:"Jogging",difficulty:"Easy",distance:"3.5 km",duration:"25–35 mins",rating:4.4,reviews:267,badge:"Heritage Run",weather:"Cloudy",temp:27,humidity:78,wind:6,color:"#2a5a4a",emoji:"🌺",description:"Shaded paths through colonial-era botanical gardens — monkeys, rare orchids, and cool forest canopy.",facilities:["Toilets","Benches","Parking","Café at entrance"],bestMonths:"Year-round",accessibility:"Fully accessible. Dog-friendly before 9 AM.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Free"},
  {id:28,name:"Penang Cycling Bypass",state:"Pulau Pinang",stateCode:"PNG",activity:"Cycling",difficulty:"Moderate",distance:"22 km",duration:"2–3 hrs",rating:4.3,reviews:119,badge:"Island Loop",weather:"Sunny",temp:30,humidity:80,wind:12,color:"#5c4a2a",emoji:"🚴",description:"Scenic coastal cycling route around Penang Island — fishing villages, temples, and sea breezes.",facilities:["Bike rental in Georgetown","Roadside hawker stalls","Public toilets"],bestMonths:"November – March",accessibility:"Some road traffic — suitable for confident riders.",tags:["Beginner"],budget:"Low"},
  {id:29,name:"Monkey Beach Trek",state:"Pulau Pinang",stateCode:"PNG",activity:"Hiking",difficulty:"Easy",distance:"5 km",duration:"2.5–3 hrs",rating:4.3,reviews:184,badge:"Beach Trek",weather:"Sunny",temp:29,humidity:81,wind:8,color:C.forest,emoji:"🐒",description:"Rainforest trail through Penang National Park to the secluded Monkey Beach — macaques, hornbills, sea views.",facilities:["Park entrance","Boat alternative","Beach","Basic amenities"],bestMonths:"October – April",accessibility:"Beginner-friendly. Can take a boat back.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:30,name:"Teluk Bahang Diving",state:"Pulau Pinang",stateCode:"PNG",activity:"Diving",difficulty:"Easy",distance:"N/A",duration:"Half Day",rating:4.2,reviews:88,badge:"Local Reef",weather:"Sunny",temp:28,humidity:78,wind:8,color:C.forest,emoji:"🤿",description:"Accessible reef diving off Penang's northwest coast — soft corals, nudibranchs, and reef fish.",facilities:["Local dive operators","Equipment rental","Speedboat transfer"],bestMonths:"October – April",accessibility:"Open Water cert or guided Discover Scuba.",tags:["Beginner"],budget:"Medium"},
  // ── Johor ──
  {id:31,name:"Gunung Ledang Trail",state:"Johor",stateCode:"JHR",activity:"Hiking",difficulty:"Hard",distance:"11 km",duration:"8–10 hrs",rating:4.6,reviews:224,badge:"Legendary",weather:"Partly Cloudy",temp:24,humidity:88,wind:9,color:C.jungle,emoji:"🌿",description:"Known as Mount Ophir, steeped in Malay folklore — a challenging jungle trek through primary rainforest.",facilities:["Park entrance","Campsite","Guides available","Water streams"],bestMonths:"March – October",accessibility:"Experienced hikers only. Permit required.",tags:["Advanced"],budget:"Low"},
  {id:32,name:"Desaru Coast Cycling",state:"Johor",stateCode:"JHR",activity:"Cycling",difficulty:"Easy",distance:"18 km",duration:"1.5–2 hrs",rating:4.2,reviews:96,badge:"Coastal Ride",weather:"Sunny",temp:31,humidity:75,wind:10,color:"#5c4a2a",emoji:"🌊",description:"Flat beachside cycling route along Desaru's 17km coastline — palm trees, white sand, and sea breeze.",facilities:["Bike rental at resort","Rest stops","Beach cafés","Toilets"],bestMonths:"November – March",accessibility:"Flat route, suitable for all ages.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Low"},
  {id:33,name:"Pulau Tinggi Dive",state:"Johor",stateCode:"JHR",activity:"Diving",difficulty:"Moderate",distance:"N/A",duration:"Full Day",rating:4.5,reviews:131,badge:"Hidden Reef",weather:"Sunny",temp:28,humidity:77,wind:8,color:C.forest,emoji:"🐢",description:"Remote island diving 45 minutes from Mersing — pristine coral walls, hawksbill turtles, and nurse sharks.",facilities:["Dive operators in Mersing","Basic beach chalet","Boat transfers"],bestMonths:"March – October",accessibility:"Open Water cert required. Remote location.",tags:["Advanced"],budget:"Medium"},
  {id:34,name:"Kota Tinggi Waterfalls Camp",state:"Johor",stateCode:"JHR",activity:"Camping",difficulty:"Easy",distance:"N/A",duration:"Overnight",rating:4.1,reviews:178,badge:"Family Camp",weather:"Partly Cloudy",temp:28,humidity:83,wind:5,color:C.jungle,emoji:"🏕️",description:"Riverside camping at the base of Kota Tinggi's jungle waterfalls — rope swings, natural pools, night sounds.",facilities:["Campsite platforms","BBQ pits","Toilets","Waterfall swimming"],bestMonths:"Year-round",accessibility:"Easy access by car. Suitable for families.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:35,name:"Mersing River Kayak",state:"Johor",stateCode:"JHR",activity:"Water Sports",difficulty:"Easy",distance:"8 km",duration:"2–3 hrs",rating:4.0,reviews:62,badge:"River Paddle",weather:"Sunny",temp:31,humidity:78,wind:6,color:"#1a6b8a",emoji:"🚣",description:"Peaceful mangrove river kayaking from Mersing town — fireflies at dusk, kingfishers, and calm waters.",facilities:["Kayak rental","Guided tours available","Life jackets","Nearby food"],bestMonths:"November – March",accessibility:"No experience needed. Guide recommended for beginners.",tags:["Family Friendly","Beginner"],budget:"Low"},
  // ── Kedah ──
  {id:36,name:"Langkawi Jet Ski & Parasailing",state:"Kedah",stateCode:"KDH",activity:"Water Sports",difficulty:"Moderate",distance:"N/A",duration:"Half Day",rating:4.6,reviews:243,badge:"Thrills Guaranteed",weather:"Sunny",temp:32,humidity:70,wind:14,color:"#1a6b8a",emoji:"🌊",description:"High-adrenaline water sports — jet skis, parasailing, flyboarding, and wakeboarding on Langkawi's waters.",facilities:["Multiple operators","Equipment provided","Safety briefing","Beachside amenities"],bestMonths:"November – April",accessibility:"Good fitness recommended. Minimum age for some activities.",tags:["Advanced"],budget:"High"},
  {id:37,name:"Gunung Jerai Summit Hike",state:"Kedah",stateCode:"KDH",activity:"Hiking",difficulty:"Moderate",distance:"5 km",duration:"3–4 hrs",rating:4.3,reviews:143,badge:"Panorama Peak",weather:"Cloudy",temp:22,humidity:87,wind:12,color:"#2a5a4a",emoji:"🌧️",description:"Kedah's iconic standalone peak rising from flat paddy plains — ancient Hindu temple at the top, sea views.",facilities:["Cable car option","Basic canteen","Toilets","Temple"],bestMonths:"March – November",accessibility:"Moderate. Cable car available as alternative.",tags:["Family Friendly"],budget:"Low"},
  {id:38,name:"Langkawi Mangrove Kayak",state:"Kedah",stateCode:"KDH",activity:"Water Sports",difficulty:"Easy",distance:"7 km",duration:"2–3 hrs",rating:4.5,reviews:189,badge:"Mangrove Magic",weather:"Partly Cloudy",temp:30,humidity:80,wind:7,color:"#1a6b8a",emoji:"🌿",description:"Guided kayak through ancient mangrove channels — monitor lizards, kingfishers, eagle spotting.",facilities:["Tour operators","Life jackets","Drinking water","Jetty transfer"],bestMonths:"November – April",accessibility:"No experience needed. Family-friendly.",tags:["Family Friendly","Beginner"],budget:"Medium"},
  {id:39,name:"Langkawi Cycling Tour",state:"Kedah",stateCode:"KDH",activity:"Cycling",difficulty:"Easy",distance:"20 km",duration:"2–3 hrs",rating:4.2,reviews:108,badge:"Island Ride",weather:"Sunny",temp:32,humidity:74,wind:10,color:"#5c4a2a",emoji:"🚴",description:"Flat coastal cycling through Langkawi's fishing villages, rice paddy fields, and beachfront roads.",facilities:["Bike rental in Kuah","Road well-marked","Seafood restaurants","Toilets"],bestMonths:"November – April",accessibility:"Flat, suitable for all levels.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:40,name:"Padang Besar Border Walk",state:"Kedah",stateCode:"KDH",activity:"Jogging",difficulty:"Easy",distance:"5 km",duration:"35–45 mins",rating:3.9,reviews:55,badge:"Cross-Border",weather:"Sunny",temp:33,humidity:72,wind:9,color:"#5c4a2a",emoji:"🏃",description:"Flat cross-border town jogging route — Thailand border market atmosphere and flat roads.",facilities:["Public toilets","Convenience stores","Parking"],bestMonths:"Year-round",accessibility:"Flat, fully accessible.",tags:["Beginner"],budget:"Free"},
  // ── Kelantan ──
  {id:41,name:"Gunung Stong Waterfall Camp",state:"Kelantan",stateCode:"KTN",activity:"Camping",difficulty:"Hard",distance:"8 km",duration:"2 Days",rating:4.7,reviews:87,badge:"Tallest Fall",weather:"Partly Cloudy",temp:24,humidity:89,wind:8,color:C.jungle,emoji:"💦",description:"Malaysia's highest waterfall at 305m — a demanding camp at the base accessible through primary rainforest.",facilities:["Campsite","Guides available","River water","Ranger post"],bestMonths:"April – October",accessibility:"Hard trail, river crossings. Guide recommended.",tags:["Advanced"],budget:"Low"},
  {id:42,name:"Jelawat Beach Run",state:"Kelantan",stateCode:"KTN",activity:"Jogging",difficulty:"Easy",distance:"6 km",duration:"40–55 mins",rating:4.0,reviews:72,badge:"Sunrise Jog",weather:"Sunny",temp:29,humidity:78,wind:12,color:"#5c4a2a",emoji:"🌅",description:"Flat beach jogging on Kelantan's undiscovered eastern coastline — empty beaches at sunrise.",facilities:["Parking","Toilet at beach","Nearby hawker food"],bestMonths:"March – August",accessibility:"Flat sand. Avoid east coast monsoon season.",tags:["Beginner","Pet Friendly"],budget:"Free"},
  {id:43,name:"Gunung Ayam Hike",state:"Kelantan",stateCode:"KTN",activity:"Hiking",difficulty:"Moderate",distance:"6 km",duration:"4–5 hrs",rating:4.2,reviews:64,badge:"Jungle Climb",weather:"Partly Cloudy",temp:25,humidity:88,wind:6,color:"#2a5a4a",emoji:"🐓",description:"Forested mountain hike through Kelantan's interior — giant ferns, waterfalls, and panoramic views.",facilities:["Trailhead parking","Village guide available","River water"],bestMonths:"April – September",accessibility:"Moderate fitness required.",tags:["Beginner"],budget:"Free"},
  {id:44,name:"Kuala Krai River Kayak",state:"Kelantan",stateCode:"KTN",activity:"Water Sports",difficulty:"Moderate",distance:"15 km",duration:"3–4 hrs",rating:4.1,reviews:48,badge:"White Water",weather:"Partly Cloudy",temp:27,humidity:86,wind:5,color:"#1a6b8a",emoji:"🚣",description:"Grade II–III rapids along the Galas River — exciting white water with calmer stretches through jungle.",facilities:["Local operators","Life jackets","Helmets","Transport back to start"],bestMonths:"April – September",accessibility:"Beginner paddlers welcome with guide.",tags:["Beginner"],budget:"Medium"},
  {id:45,name:"KB Park Cycling Loop",state:"Kelantan",stateCode:"KTN",activity:"Cycling",difficulty:"Easy",distance:"10 km",duration:"45–60 mins",rating:3.9,reviews:91,badge:"Morning Ride",weather:"Sunny",temp:31,humidity:78,wind:7,color:"#5c4a2a",emoji:"🚴",description:"Paved cycle loop around Kota Bharu's riverside park and cultural village — quiet mornings.",facilities:["Bike rental","Toilets","Food stalls","Cultural exhibits"],bestMonths:"Year-round",accessibility:"Flat, fully accessible.",tags:["Family Friendly","Beginner"],budget:"Low"},
  // ── Terengganu ──
  {id:46,name:"Perhentian Island Reef Dive",state:"Terengganu",stateCode:"TRG",activity:"Diving",difficulty:"Easy",distance:"N/A",duration:"Half Day",rating:4.8,reviews:376,badge:"Hidden Gem",weather:"Sunny",temp:28,humidity:75,wind:5,color:C.forest,emoji:"🐢",description:"Crystal-clear waters host vibrant coral gardens, sea turtles, and reef sharks.",facilities:["Dive shops on island","Equipment rental","Accommodation","Beach restaurants"],bestMonths:"May – September",accessibility:"Beginner-friendly. Snorkeling also available.",tags:["Family Friendly","Beginner"],budget:"Medium"},
  {id:47,name:"Kenyir Lake Kayak",state:"Terengganu",stateCode:"TRG",activity:"Water Sports",difficulty:"Easy",distance:"N/A",duration:"Half Day",rating:4.3,reviews:142,badge:"Inland Sea",weather:"Sunny",temp:29,humidity:72,wind:6,color:"#1a6b8a",emoji:"🏊",description:"Southeast Asia's largest man-made lake — calm freshwater kayaking, swimming, and boat tours.",facilities:["Resort accommodation","Boat rental","Fishing","Waterfalls nearby"],bestMonths:"March – September",accessibility:"All levels welcome.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:48,name:"Bukit Bauk Trail",state:"Terengganu",stateCode:"TRG",activity:"Hiking",difficulty:"Easy",distance:"3.5 km",duration:"2–2.5 hrs",rating:4.1,reviews:88,badge:"Coastal Views",weather:"Sunny",temp:29,humidity:80,wind:10,color:C.forest,emoji:"🌊",description:"Gentle forested hill walk with lookout points over the South China Sea and fishing village below.",facilities:["Parking","Trailhead signage","Nearby food stalls"],bestMonths:"March – September",accessibility:"Beginner-friendly.",tags:["Family Friendly","Beginner"],budget:"Free"},
  {id:49,name:"Redang Island Beach Camp",state:"Terengganu",stateCode:"TRG",activity:"Camping",difficulty:"Easy",distance:"N/A",duration:"Overnight",rating:4.5,reviews:118,badge:"Island Camp",weather:"Sunny",temp:29,humidity:74,wind:8,color:C.jungle,emoji:"🏕️",description:"Glamping and basic camping on Redang's white-sand beach — bioluminescent plankton at night.",facilities:["Beach chalets","Camp fires allowed","Snorkeling","Toilets"],bestMonths:"May – September",accessibility:"Boat access from Merang jetty.",tags:["Family Friendly","Beginner"],budget:"Medium"},
  {id:50,name:"Marang Coastal Jog",state:"Terengganu",stateCode:"TRG",activity:"Jogging",difficulty:"Easy",distance:"5 km",duration:"35–45 mins",rating:3.9,reviews:54,badge:"Fishing Village",weather:"Sunny",temp:30,humidity:77,wind:11,color:"#5c4a2a",emoji:"🎣",description:"Flat coastal road jog through the traditional fishing village of Marang with early-morning boat activity.",facilities:["Parking","Seafood stalls","Beach access"],bestMonths:"March – September",accessibility:"Flat, fully accessible.",tags:["Beginner","Pet Friendly"],budget:"Free"},
  // ── Negeri Sembilan ──
  {id:51,name:"Gunung Angsi Trek",state:"Negeri Sembilan",stateCode:"NSN",activity:"Hiking",difficulty:"Moderate",distance:"8 km",duration:"4–5 hrs",rating:4.4,reviews:189,badge:"Minang Trail",weather:"Partly Cloudy",temp:26,humidity:83,wind:7,color:"#2a5a4a",emoji:"🌿",description:"Popular forest trail in Gunung Angsi Wildlife Reserve — diverse birdlife and a scenic ridge walk.",facilities:["Trailhead parking","Trail markers","Water streams"],bestMonths:"Year-round",accessibility:"Moderate fitness. Trail shoes recommended.",tags:["Beginner"],budget:"Free"},
  {id:52,name:"Seremban Lake Gardens Jog",state:"Negeri Sembilan",stateCode:"NSN",activity:"Jogging",difficulty:"Easy",distance:"4 km",duration:"25–35 mins",rating:4.0,reviews:136,badge:"Heritage Run",weather:"Sunny",temp:31,humidity:74,wind:8,color:"#5c4a2a",emoji:"🌸",description:"Paved jogging path around colonial-era lake gardens — fountains, mature trees, and early-morning exercise crowds.",facilities:["Toilets","Water fountains","Shaded paths","Parking"],bestMonths:"Year-round",accessibility:"Flat, fully accessible.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Free"},
  {id:53,name:"Port Dickson Beach Cycling",state:"Negeri Sembilan",stateCode:"NSN",activity:"Cycling",difficulty:"Easy",distance:"16 km",duration:"1.5–2 hrs",rating:4.1,reviews:112,badge:"Beach Cruiser",weather:"Sunny",temp:31,humidity:78,wind:10,color:"#5c4a2a",emoji:"🚴",description:"Flat coastal road cycling along Port Dickson's 18km beach — resort strip, seafood restaurants, sea breezes.",facilities:["Bike rental at resorts","Road cafés","Toilets","Hotels"],bestMonths:"November – March",accessibility:"Flat, suitable for all levels.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:54,name:"PD Beach Swimming",state:"Negeri Sembilan",stateCode:"NSN",activity:"Swimming",difficulty:"Easy",distance:"N/A",duration:"Half Day",rating:3.9,reviews:203,badge:"Weekend Splash",weather:"Sunny",temp:29,humidity:80,wind:8,color:"#1a6b8a",emoji:"🏊",description:"Calm sheltered bays along Port Dickson's coastline — lifeguard-patrolled during weekends and holidays.",facilities:["Lifeguards (weekends)","Beach showers","Parking","Hawker food"],bestMonths:"November – March",accessibility:"All levels. Some beaches have sand bar slopes.",tags:["Family Friendly","Beginner"],budget:"Free"},
  {id:55,name:"Lenggeng Waterfall Camp",state:"Negeri Sembilan",stateCode:"NSN",activity:"Camping",difficulty:"Easy",distance:"2 km",duration:"Overnight",rating:4.2,reviews:77,badge:"Waterfall Bliss",weather:"Partly Cloudy",temp:27,humidity:85,wind:4,color:C.jungle,emoji:"🏕️",description:"Short walk to a multi-tiered waterfall with a dedicated campsite — ideal beginner overnight adventure.",facilities:["Campsite","BBQ pits","Toilets","Carpark"],bestMonths:"Year-round",accessibility:"Short trail, accessible for most fitness levels.",tags:["Family Friendly","Beginner"],budget:"Low"},
  // ── Melaka ──
  {id:56,name:"Bukit China Heritage Walk",state:"Melaka",stateCode:"MLK",activity:"Jogging",difficulty:"Easy",distance:"3 km",duration:"25–35 mins",rating:4.1,reviews:145,badge:"History Run",weather:"Sunny",temp:32,humidity:76,wind:7,color:"#5c4a2a",emoji:"🏛️",description:"Loop trail through the world's oldest and largest Chinese cemetery — hilltop views of Melaka City.",facilities:["Toilets at base","Parking","Historical markers","Hawker food nearby"],bestMonths:"Year-round",accessibility:"Paved path, moderate incline at top.",tags:["Family Friendly","Beginner"],budget:"Free"},
  {id:57,name:"Ayer Keroh Cycling Park",state:"Melaka",stateCode:"MLK",activity:"Cycling",difficulty:"Easy",distance:"10 km",duration:"45–60 mins",rating:4.0,reviews:98,badge:"Family Ride",weather:"Sunny",temp:32,humidity:73,wind:8,color:"#5c4a2a",emoji:"🚴",description:"Paved cycling loops through Ayer Keroh's recreation area — Zoo Melaka, botanical garden, and mini Malaysia park.",facilities:["Bike rental","Toilets","Parking","Nearby restaurants"],bestMonths:"Year-round",accessibility:"Flat, fully accessible. Great for families.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:58,name:"Cape Rachado Lighthouse Hike",state:"Melaka",stateCode:"MLK",activity:"Hiking",difficulty:"Easy",distance:"2.5 km",duration:"1.5 hrs",rating:4.3,reviews:113,badge:"Lighthouse Trail",weather:"Partly Cloudy",temp:30,humidity:80,wind:9,color:C.forest,emoji:"🔦",description:"Short forest trail to Malaysia's oldest lighthouse — Portuguese-era views across the Straits of Malacca.",facilities:["Parking","Trail markers","Lighthouse viewpoint"],bestMonths:"Year-round",accessibility:"Short and easy. Suitable for families.",tags:["Family Friendly","Beginner"],budget:"Free"},
  {id:59,name:"Melaka River Kayak",state:"Melaka",stateCode:"MLK",activity:"Water Sports",difficulty:"Easy",distance:"5 km",duration:"1.5–2 hrs",rating:4.2,reviews:166,badge:"Heritage Paddle",weather:"Sunny",temp:31,humidity:77,wind:6,color:"#1a6b8a",emoji:"🚣",description:"Guided kayak along the Melaka River past heritage shophouses, murals, and the iconic red clock tower.",facilities:["Kayak rental","Life jackets","Guided tours","Riverside cafés"],bestMonths:"Year-round",accessibility:"No experience needed. Calm river.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:60,name:"Hang Tuah Hill Trail",state:"Melaka",stateCode:"MLK",activity:"Hiking",difficulty:"Easy",distance:"3 km",duration:"1.5–2 hrs",rating:3.9,reviews:82,badge:"Legend Hill",weather:"Partly Cloudy",temp:30,humidity:81,wind:7,color:"#2a5a4a",emoji:"⚔️",description:"Forest trail to the hill associated with legendary warrior Hang Tuah — banyan trees and panoramic views.",facilities:["Parking","Trail markers","Historical signage"],bestMonths:"Year-round",accessibility:"Easy. Suitable for families.",tags:["Family Friendly","Beginner"],budget:"Free"},
  // ── Perlis ──
  {id:61,name:"Wang Kelian Cross-Border Trail",state:"Perlis",stateCode:"PLS",activity:"Hiking",difficulty:"Easy",distance:"4 km",duration:"2–3 hrs",rating:4.0,reviews:53,badge:"Border Trek",weather:"Sunny",temp:33,humidity:72,wind:8,color:"#2a5a4a",emoji:"🌏",description:"Short forested hill trail leading to the Thai border — limestone outcrops, cave temples, and viewpoints.",facilities:["Parking","Border market nearby","Basic trail markers"],bestMonths:"November – March",accessibility:"Easy terrain. Suitable for families.",tags:["Family Friendly","Beginner"],budget:"Free"},
  {id:62,name:"Perlis State Park Cave Walk",state:"Perlis",stateCode:"PLS",activity:"Hiking",difficulty:"Moderate",distance:"5 km",duration:"3 hrs",rating:4.3,reviews:71,badge:"Cave Country",weather:"Partly Cloudy",temp:31,humidity:76,wind:7,color:"#3d2c1a",emoji:"🦇",description:"Limestone hill cave walk in Perlis State Park — unique geology, bats, rare orchids, and swiftlet colonies.",facilities:["Park entrance fee","Guided tours","Trail markers","Toilets"],bestMonths:"October – April",accessibility:"Moderate. Some cave sections require crouching.",tags:["Family Friendly"],budget:"Low"},
  {id:63,name:"Kangar Town Cycling",state:"Perlis",stateCode:"PLS",activity:"Cycling",difficulty:"Easy",distance:"8 km",duration:"40–50 mins",rating:3.8,reviews:44,badge:"Flat Ride",weather:"Sunny",temp:34,humidity:70,wind:9,color:"#5c4a2a",emoji:"🚴",description:"Flat urban cycling through Malaysia's smallest state capital — paddy field scenery and fruit orchards.",facilities:["Basic bike rental","Food stalls","Quiet roads"],bestMonths:"November – April",accessibility:"Fully flat. Suitable for all levels.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:64,name:"Padang Besar Jogging Track",state:"Perlis",stateCode:"PLS",activity:"Jogging",difficulty:"Easy",distance:"3 km",duration:"20–30 mins",rating:3.7,reviews:38,badge:"Border Town",weather:"Sunny",temp:33,humidity:71,wind:10,color:"#5c4a2a",emoji:"👟",description:"Purpose-built jogging track in Padang Besar recreation park — flat and shaded.",facilities:["Toilets","Water fountain","Parking","Gym equipment"],bestMonths:"Year-round",accessibility:"Flat, fully accessible.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Free"},
  // ── Kuala Lumpur ──
  {id:65,name:"Bukit Tabur Ridge",state:"Kuala Lumpur",stateCode:"KL",activity:"Hiking",difficulty:"Moderate",distance:"3.5 km",duration:"3–4 hrs",rating:4.4,reviews:567,badge:"City Escape",weather:"Partly Cloudy",temp:28,humidity:82,wind:7,color:"#2a5a4a",emoji:"🏙️",description:"Dramatic quartzite ridge hike 15 minutes from KLCC — razor-edge ridgelines with city skyline views.",facilities:["Free parking nearby","Trail markers","Nearby convenience stores"],bestMonths:"Year-round",accessibility:"Moderate fitness. Some scrambling sections.",tags:["Beginner"],budget:"Free"},
  {id:66,name:"KL Tower Forest Hike",state:"Kuala Lumpur",stateCode:"KL",activity:"Hiking",difficulty:"Easy",distance:"1.5 km",duration:"45 mins",rating:4.0,reviews:312,badge:"Urban Trek",weather:"Partly Cloudy",temp:29,humidity:80,wind:6,color:C.forest,emoji:"📡",description:"Forested trail ascending Bukit Nanas — the only remaining primary forest in KL, with KL Tower looming above.",facilities:["Interpretive trail","Toilets","Free entry","Nearby LRT"],bestMonths:"Year-round",accessibility:"Short and easy. Suitable for all.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Free"},
  {id:67,name:"Kepong Metro Park Jog",state:"Kuala Lumpur",stateCode:"KL",activity:"Jogging",difficulty:"Easy",distance:"5 km",duration:"35–45 mins",rating:4.1,reviews:198,badge:"City Lungs",weather:"Partly Cloudy",temp:30,humidity:78,wind:7,color:"#5c4a2a",emoji:"🏃",description:"Lakeside jogging path through KL's largest metropolitan park — fitness stations, shaded canopy walks.",facilities:["Toilets","Fitness stations","Parking","Canteen"],bestMonths:"Year-round",accessibility:"Flat, fully accessible.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Free"},
  {id:68,name:"Putrajaya Garden Cycling",state:"Kuala Lumpur",stateCode:"KL",activity:"Cycling",difficulty:"Easy",distance:"12 km",duration:"1–1.5 hrs",rating:4.2,reviews:144,badge:"Garden Loop",weather:"Sunny",temp:31,humidity:72,wind:9,color:"#5c4a2a",emoji:"🌸",description:"Cycling through KL's botanical gardens and Perdana Lake Gardens — flamingos, deer, and colonial monuments.",facilities:["Bike rental","Toilets","Food court","Parking"],bestMonths:"Year-round",accessibility:"Flat, fully accessible.",tags:["Family Friendly","Beginner"],budget:"Low"},
  // ── Putrajaya ──
  {id:69,name:"Putrajaya Lake Loop Cycling",state:"Putrajaya",stateCode:"PTJ",activity:"Cycling",difficulty:"Easy",distance:"14 km",duration:"1–2 hrs",rating:4.5,reviews:213,badge:"Beginner Pick",weather:"Sunny",temp:30,humidity:70,wind:10,color:"#5c4a2a",emoji:"🚴",description:"Fully paved lakeside cycling route circling Putrajaya Lake with iconic bridge views.",facilities:["Bike rental","Rest areas","Cafés nearby","Public toilets"],bestMonths:"October – March",accessibility:"Flat route, fully accessible. Bike rental available.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:70,name:"Putrajaya Waterfront Jog",state:"Putrajaya",stateCode:"PTJ",activity:"Jogging",difficulty:"Easy",distance:"5 km",duration:"30–40 mins",rating:4.2,reviews:321,badge:"City Jog",weather:"Sunny",temp:31,humidity:68,wind:9,color:"#5c4a2a",emoji:"👟",description:"Flat paved waterfront path alongside Putrajaya Lake — government district architecture and morning bird life.",facilities:["Public toilets","Water stations","Parking","Nearby cafés"],bestMonths:"Year-round",accessibility:"Fully accessible. Suitable for all ages.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Free"},
  {id:71,name:"Putrajaya Wetlands Bird Walk",state:"Putrajaya",stateCode:"PTJ",activity:"Hiking",difficulty:"Easy",distance:"3 km",duration:"1.5–2 hrs",rating:4.3,reviews:112,badge:"Birdwatch Trail",weather:"Sunny",temp:30,humidity:74,wind:8,color:C.forest,emoji:"🦅",description:"Boardwalk trail through Putrajaya's constructed wetlands — over 150 bird species including migratory visitors.",facilities:["Free entry","Boardwalk","Observation towers","Interpretive signs"],bestMonths:"October – March",accessibility:"Flat boardwalk, fully accessible.",tags:["Family Friendly","Beginner","Pet Friendly"],budget:"Free"},
  // ── Labuan ──
  {id:72,name:"Labuan Wreck Diving",state:"Labuan",stateCode:"LBN",activity:"Diving",difficulty:"Moderate",distance:"N/A",duration:"Full Day",rating:4.7,reviews:118,badge:"Wreck Specialist",weather:"Sunny",temp:29,humidity:77,wind:8,color:C.forest,emoji:"⚓",description:"World-class wreck diving — four WWII-era ships resting 30–50m down, encrusted with vibrant soft corals.",facilities:["Dive operators","Equipment rental","Guided dives","Day trips from Kota Kinabalu"],bestMonths:"March – October",accessibility:"Advanced Open Water cert recommended.",tags:["Advanced"],budget:"Medium"},
  {id:73,name:"Labuan Garden Cycling",state:"Labuan",stateCode:"LBN",activity:"Cycling",difficulty:"Easy",distance:"15 km",duration:"1–1.5 hrs",rating:4.0,reviews:67,badge:"Island Loop",weather:"Sunny",temp:30,humidity:79,wind:9,color:"#5c4a2a",emoji:"🚴",description:"Flat island cycling past Labuan's duty-free shops, WWII cemetery, and quiet fishing kampungs.",facilities:["Bike rental in town","Flat roads","Duty-free shops","Cafés"],bestMonths:"Year-round",accessibility:"Flat, suitable for all.",tags:["Family Friendly","Beginner"],budget:"Low"},
  {id:74,name:"Labuan Beach Walk",state:"Labuan",stateCode:"LBN",activity:"Jogging",difficulty:"Easy",distance:"4 km",duration:"25–35 mins",rating:3.8,reviews:52,badge:"Sunset Jog",weather:"Sunny",temp:30,humidity:77,wind:10,color:"#5c4a2a",emoji:"🌅",description:"Beachfront jogging path with views of the South China Sea at sunrise and sunset.",facilities:["Public beach","Parking","Nearby hawker food"],bestMonths:"Year-round",accessibility:"Flat sand and promenade.",tags:["Beginner","Pet Friendly"],budget:"Free"},
];

export const LEADERBOARD_DATA = [
  {rank:1,name:"Ahmad Razif",km:312,states:11,checkins:24,medal:"🥇"},
  {rank:2,name:"Siti Nurhaliza",km:278,states:9,checkins:20,medal:"🥈"},
  {rank:3,name:"Low Jun Feng",km:245,states:8,checkins:17,medal:"🥉"},
  {rank:4,name:"Priya Marimuthu",km:198,states:7,checkins:13,medal:""},
  {rank:5,name:"Fong Xin Tong",km:176,states:6,checkins:11,medal:""},
  {rank:6,name:"Wilson Choong",km:154,states:5,checkins:9,medal:""},
  {rank:7,name:"Lim Rou Yu",km:132,states:4,checkins:8,medal:""},
];

export const BADGES_DATA = [
  {icon:"🏔️",name:"Summit Seeker",desc:"Climbed 5 peaks",requirement:5,progress:3,earned:false},
  {icon:"🌊",name:"Deep Explorer",desc:"Dived 3 sites",requirement:3,progress:3,earned:true},
  {icon:"🗺️",name:"State Hopper",desc:"Visited 5 states",requirement:5,progress:5,earned:true},
  {icon:"🔥",name:"Iron Trailblazer",desc:"Log 100 km total",requirement:100,progress:47,earned:false},
  {icon:"🌿",name:"Gem Hunter",desc:"Find 3 hidden gems",requirement:3,progress:1,earned:false},
  {icon:"⭐",name:"Community Star",desc:"Write 10 reviews",requirement:10,progress:4,earned:false},
  {icon:"🚴",name:"Wheel Warrior",desc:"Cycle 50 km total",requirement:50,progress:50,earned:true},
  {icon:"🏕️",name:"Wild Camper",desc:"Camp at 2 sites",requirement:2,progress:1,earned:false},
];

export const AI_RESPONSES: Record<string,string> = {
  default:"I'm your SeekMY outdoor guide 🌿 Ask me about hiking, diving, cycling, camping, gear, or any Malaysian destination!",
  hiking:"For hiking in Malaysia, start with Broga Hill (Selangor) — 4.2 km, beginner-friendly, stunning sunrise. Pack: 2L water, trail shoes, SPF 50+ sunscreen, rain jacket. Start before 7 AM.",
  diving:"Malaysia has world-class dive sites! Sipadan (Sabah) is globally top-10. Perhentian and Tioman suit beginners. Minimum: Open Water certification. Always dive with a buddy.",
  cycling:"Try the Putrajaya Lake Loop (14 km, flat) or Penang Hill backroads. Wear a helmet, carry a repair kit, ride early to avoid heat.",
  camping:"Endau-Rompin National Park (Pahang) is Malaysia's best camping — ancient rainforest, waterfalls, rare wildlife. Always use a certified guide.",
  gear:"Malaysia essentials: trail shoes, quick-dry clothing, rain poncho, 2–3L water, SPF 50+ sunscreen, DEET 30%+ repellent, headlamp, basic first aid, portable charger.",
  beginner:"Best beginner spots: 🌄 Broga Hill (easy hike) · 🚴 Putrajaya Loop (flat cycling) · 🐢 Perhentian Islands (snorkeling) · 🏊 Kenyir Lake (calm swimming).",
  sipadan:"Sipadan Island, Sabah — top-10 dive sites globally. Expect hammerhead sharks, sea turtle highways, barracuda tornadoes. Open Water cert required. Book 3–6 months ahead!",
  weather:"Malaysia has two monsoon seasons: Northeast (Nov–Feb) affects east coast. Southwest (May–Sep) affects west coast. Afternoon thunderstorms are common year-round!",
};



/** Approximate GPS for map markers (Malaysia) */
export const LOCATION_COORDS: Record<number, {lat:number; lng:number}> = {
  1:{lat:6.075,lng:116.558}, 2:{lat:4.115,lng:118.628}, 3:{lat:5.95,lng:116.25},
  4:{lat:5.875,lng:117.95}, 5:{lat:4.48,lng:118.61}, 6:{lat:1.717,lng:110.447},
  7:{lat:1.74,lng:110.33}, 8:{lat:1.735,lng:110.335}, 9:{lat:1.56,lng:110.345},
  10:{lat:4.05,lng:114.82}, 11:{lat:2.925,lng:101.92}, 12:{lat:3.236,lng:101.635},
  13:{lat:3.237,lng:101.684}, 14:{lat:3.23,lng:101.88}, 15:{lat:3.08,lng:101.55},
  16:{lat:4.383,lng:102.4}, 17:{lat:2.79,lng:104.17}, 18:{lat:4.12,lng:103.39},
  19:{lat:2.45,lng:103.2}, 20:{lat:3.42,lng:101.79}, 21:{lat:4.47,lng:101.38},
  22:{lat:5.55,lng:101.4}, 23:{lat:4.6,lng:101.08}, 24:{lat:4.22,lng:100.55},
  25:{lat:4.65,lng:101.27}, 26:{lat:5.42,lng:100.27}, 27:{lat:5.435,lng:100.29},
  28:{lat:5.35,lng:100.3}, 29:{lat:5.45,lng:100.2}, 30:{lat:5.46,lng:100.2},
  31:{lat:2.37,lng:102.62}, 32:{lat:1.54,lng:104.27}, 33:{lat:2.3,lng:104.1},
  34:{lat:1.76,lng:103.9}, 35:{lat:2.43,lng:103.84}, 36:{lat:6.35,lng:99.8},
  37:{lat:5.79,lng:100.43}, 38:{lat:6.35,lng:99.75}, 39:{lat:6.32,lng:99.85},
  40:{lat:6.66,lng:100.32}, 41:{lat:5.34,lng:101.97}, 42:{lat:6.0,lng:102.35},
  43:{lat:5.7,lng:102.0}, 44:{lat:5.53,lng:102.2},
  71:{lat:2.93,lng:101.68}, 72:{lat:5.28,lng:115.24}, 73:{lat:5.28,lng:115.24}, 74:{lat:5.29,lng:115.25},
};

export const ACTIVITY_SPECIFIC: Record<number, {certification?:string; visibility?:string; entryType?:string; marineLife?:string; maxDepth?:string}> = {
  2: {certification:"Open Water minimum", visibility:"15–30 m", entryType:"Boat", marineLife:"Turtles, reef sharks, barracuda", maxDepth:"40 m"},
  5: {certification:"None (snorkel)", visibility:"8–15 m", entryType:"Beach / boat", marineLife:"Reef fish, starfish"},
  17: {certification:"Open Water or Discover Scuba", visibility:"10–20 m", entryType:"Shore / boat", marineLife:"Coral gardens, reef fish"},
  30: {certification:"Open Water or Discover Scuba", visibility:"5–12 m", entryType:"Boat", marineLife:"Soft coral, nudibranchs"},
  33: {certification:"Open Water", visibility:"15–25 m", entryType:"Boat", marineLife:"Hawksbill turtles, nurse sharks"},
  72: {certification:"Advanced Open Water recommended", visibility:"10–20 m", entryType:"Boat", marineLife:"Wreck corals, reef fish", maxDepth:"50 m"},
};

export const LOCATION_CONTRIBUTORS: Record<number, {id:string; name:string; role:string; area:string; verified:boolean}[]> = {
  1: [{id:"c1", name:"Sabah Alpine Guides", role:"Mountain guide", area:"Sabah", verified:true}],
  11: [{id:"c2", name:"Broga Trail Runners", role:"Hiking group", area:"Selangor", verified:true}],
  16: [{id:"c3", name:"Taman Negara Eco Tours", role:"Jungle guide", area:"Pahang", verified:true}],
  2: [{id:"c4", name:"Sipadan Dive Masters", role:"Dive instructor", area:"Sabah", verified:true}],
};

export function enrichLocation(loc: Location): Location {
  const c = LOCATION_COORDS[loc.id];
  const as = ACTIVITY_SPECIFIC[loc.id];
  const contrib = LOCATION_CONTRIBUTORS[loc.id];
  return {
    ...loc,
    ...(c ? { lat: c.lat, lng: c.lng } : {}),
    ...(as ? { activitySpecific: as } : {}),
    ...(contrib ? { contributors: contrib } : {}),
  };
}

export const LOCATIONS_ENRICHED: Location[] = LOCATIONS.map(enrichLocation);
