/** Seed outdoor locations across Malaysia for local mode (no Base44). */

export const SEED_LOCATIONS = [
  {
    id: "loc-1",
    name: "Gunung Kinabalu",
    state: "Sabah",
    activity_types: ["Hiking", "Camping"],
    difficulty: "Hard",
    description: "Malaysia's highest peak at 4,095m. A challenging multi-day climb through cloud forests to alpine summit.",
    distance_km: 17,
    duration_hours: 48,
    facilities: ["Rest houses", "Toilets", "Guides"],
    accessibility: "Permit required",
    best_months: ["Mar", "Apr", "Jul", "Aug"],
    latitude: 6.075,
    longitude: 116.558,
    image_url: "/images/location-gunung-kinabalu.jpg",
    is_hidden_gem: false,
    is_family_friendly: false,
    is_pet_friendly: false,
    is_free: false,
    entry_fee: 200,
    avg_rating: 4.8,
    review_count: 320,
    status: "active",
  },
  {
    id: "loc-2",
    name: "Taman Negara National Park",
    state: "Pahang",
    activity_types: ["Hiking", "Camping", "Water Sports"],
    difficulty: "Moderate",
    description: "One of the world's oldest rainforests. Canopy walks, river trails, and wildlife spotting.",
    distance_km: 8,
    duration_hours: 6,
    facilities: ["Chalets", "Campsites", "Restaurants"],
    accessibility: "Boat or road access",
    best_months: ["Mar", "Apr", "May", "Jun"],
    latitude: 4.383,
    longitude: 102.4,
    image_url: "/images/location-taman-negara.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: false,
    is_free: false,
    entry_fee: 5,
    avg_rating: 4.6,
    review_count: 510,
    status: "active",
  },
  {
    id: "loc-3",
    name: "Pulau Perhentian",
    state: "Terengganu",
    activity_types: ["Diving", "Swimming", "Water Sports"],
    difficulty: "Easy",
    description: "Crystal-clear waters and vibrant coral reefs. Ideal for snorkeling and scuba diving.",
    distance_km: 2,
    duration_hours: 4,
    facilities: ["Resorts", "Dive shops", "Restaurants"],
    accessibility: "Ferry from Kuala Besut",
    best_months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    latitude: 5.9167,
    longitude: 102.7333,
    image_url: "/images/location-perhentian.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: false,
    is_free: false,
    entry_fee: 0,
    avg_rating: 4.7,
    review_count: 890,
    status: "active",
  },
  {
    id: "loc-4",
    name: "Broga Hill",
    state: "Selangor",
    activity_types: ["Hiking", "Trail Running", "Jogging"],
    difficulty: "Easy",
    description: "Popular sunrise hike near KL. Short steep climb with panoramic views of the city and hills.",
    distance_km: 3.5,
    duration_hours: 2,
    facilities: ["Parking", "Food stalls"],
    accessibility: "Open access",
    best_months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    latitude: 2.9333,
    longitude: 101.8833,
    image_url: "/images/location-broga-hill.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: true,
    is_free: true,
    entry_fee: 0,
    avg_rating: 4.3,
    review_count: 1200,
    status: "active",
  },
  {
    id: "loc-5",
    name: "Bukit Broga Sunrise Trail",
    state: "Negeri Sembilan",
    activity_types: ["Hiking", "Trail Running"],
    difficulty: "Easy",
    description: "Lesser-known extension near Broga with quieter paths and great morning light.",
    distance_km: 4,
    duration_hours: 2.5,
    facilities: ["Parking"],
    accessibility: "Open access",
    best_months: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    latitude: 2.94,
    longitude: 101.89,
    image_url: "/images/location-broga-sunrise.jpg",
    is_hidden_gem: true,
    is_family_friendly: true,
    is_pet_friendly: true,
    is_free: true,
    entry_fee: 0,
    avg_rating: 4.5,
    review_count: 85,
    status: "active",
  },
  {
    id: "loc-6",
    name: "FRIM Kepong Canopy Walk",
    state: "Selangor",
    activity_types: ["Hiking", "Jogging"],
    difficulty: "Easy",
    description: "Forest Research Institute Malaysia – canopy walkway and easy forest trails near Kuala Lumpur.",
    distance_km: 5,
    duration_hours: 2,
    facilities: ["Parking", "Cafe", "Toilets"],
    accessibility: "Entry fee",
    best_months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    latitude: 3.2333,
    longitude: 101.6333,
    image_url: "/images/location-frim.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: false,
    is_free: false,
    entry_fee: 5,
    avg_rating: 4.4,
    review_count: 650,
    status: "active",
  },
  {
    id: "loc-7",
    name: "Gunung Nuang",
    state: "Selangor",
    activity_types: ["Hiking", "Trail Running"],
    difficulty: "Hard",
    description: "Tough day hike to one of Selangor's highest peaks. Muddy trails and river crossings.",
    distance_km: 16,
    duration_hours: 10,
    facilities: ["Parking", "Basic shelters"],
    accessibility: "Open access",
    best_months: ["Mar", "Apr", "May", "Jun", "Jul", "Aug"],
    latitude: 3.2667,
    longitude: 101.8833,
    image_url: "/images/location-gunung-nuang.jpg",
    is_hidden_gem: false,
    is_family_friendly: false,
    is_pet_friendly: false,
    is_free: true,
    entry_fee: 0,
    avg_rating: 4.5,
    review_count: 410,
    status: "active",
  },
  {
    id: "loc-8",
    name: "Pulau Tioman",
    state: "Pahang",
    activity_types: ["Diving", "Swimming", "Hiking", "Water Sports"],
    difficulty: "Easy",
    description: "Island paradise with reefs, jungle trails, and quiet beaches. Great for multi-activity trips.",
    distance_km: 6,
    duration_hours: 5,
    facilities: ["Resorts", "Dive centers", "Ferry"],
    accessibility: "Ferry from Mersing",
    best_months: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    latitude: 2.8,
    longitude: 104.1667,
    image_url: "/images/location-tioman.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: false,
    is_free: false,
    entry_fee: 0,
    avg_rating: 4.6,
    review_count: 720,
    status: "active",
  },
  {
    id: "loc-9",
    name: "Cameron Highlands Tea Trails",
    state: "Pahang",
    activity_types: ["Hiking", "Cycling", "Jogging"],
    difficulty: "Easy",
    description: "Cool highland walks through tea plantations and mossy forests. Perfect for families.",
    distance_km: 5,
    duration_hours: 3,
    facilities: ["Cafes", "Parking", "Hotels"],
    accessibility: "Open access",
    best_months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    latitude: 4.4693,
    longitude: 101.3845,
    image_url: "/images/location-cameron.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: true,
    is_free: true,
    entry_fee: 0,
    avg_rating: 4.5,
    review_count: 980,
    status: "active",
  },
  {
    id: "loc-10",
    name: "Batu Caves Rock Climbing",
    state: "Selangor",
    activity_types: ["Rock Climbing", "Hiking"],
    difficulty: "Moderate",
    description: "Limestone cliffs near the famous temple. Sport climbing routes for various levels.",
    distance_km: 1,
    duration_hours: 3,
    facilities: ["Parking", "Shops"],
    accessibility: "Open access",
    best_months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    latitude: 3.2379,
    longitude: 101.684,
    image_url: "/images/location-batu-caves.jpg",
    is_hidden_gem: true,
    is_family_friendly: false,
    is_pet_friendly: false,
    is_free: true,
    entry_fee: 0,
    avg_rating: 4.4,
    review_count: 150,
    status: "active",
  },
  {
    id: "loc-11",
    name: "Penang National Park",
    state: "Pulau Pinang",
    activity_types: ["Hiking", "Swimming", "Camping"],
    difficulty: "Moderate",
    description: "Coastal rainforest trails leading to Monkey Beach and turtle nesting sites.",
    distance_km: 7,
    duration_hours: 5,
    facilities: ["Park office", "Campsites"],
    accessibility: "Park entry",
    best_months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    latitude: 5.4667,
    longitude: 100.2,
    image_url: "/images/location-penang-park.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: false,
    is_free: false,
    entry_fee: 5,
    avg_rating: 4.5,
    review_count: 430,
    status: "active",
  },
  {
    id: "loc-12",
    name: "Mulu Caves",
    state: "Sarawak",
    activity_types: ["Hiking", "Camping"],
    difficulty: "Moderate",
    description: "UNESCO World Heritage site with vast cave systems and rainforest treks.",
    distance_km: 10,
    duration_hours: 8,
    facilities: ["Park lodges", "Guides"],
    accessibility: "Flight to Mulu + park permit",
    best_months: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    latitude: 4.05,
    longitude: 114.8,
    image_url: "/images/location-mulu.jpg",
    is_hidden_gem: false,
    is_family_friendly: false,
    is_pet_friendly: false,
    is_free: false,
    entry_fee: 30,
    avg_rating: 4.9,
    review_count: 280,
    status: "active",
  },
  {
    id: "loc-13",
    name: "Kota Kinabalu Dive Sites",
    state: "Sabah",
    activity_types: ["Diving", "Swimming", "Water Sports"],
    difficulty: "Easy",
    description: "Tunku Abdul Rahman Marine Park – easy boat dives and snorkeling near KK.",
    distance_km: 3,
    duration_hours: 4,
    facilities: ["Dive operators", "Boats"],
    accessibility: "Boat from KK",
    best_months: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    latitude: 5.97,
    longitude: 116.0,
    image_url: "/images/location-kk-dive.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: false,
    is_free: false,
    entry_fee: 20,
    avg_rating: 4.6,
    review_count: 540,
    status: "active",
  },
  {
    id: "loc-14",
    name: "Bukit Gasing",
    state: "Selangor",
    activity_types: ["Hiking", "Trail Running", "Jogging"],
    difficulty: "Easy",
    description: "Urban forest trail between KL and Petaling Jaya. Popular after-work hike.",
    distance_km: 4,
    duration_hours: 2,
    facilities: ["Parking", "Food nearby"],
    accessibility: "Open access",
    best_months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    latitude: 3.1,
    longitude: 101.65,
    image_url: "/images/location-bukit-gasing.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: true,
    is_free: true,
    entry_fee: 0,
    avg_rating: 4.2,
    review_count: 1100,
    status: "active",
  },
  {
    id: "loc-15",
    name: "Endau-Rompin National Park",
    state: "Johor",
    activity_types: ["Hiking", "Camping", "Swimming"],
    difficulty: "Hard",
    description: "Remote wilderness with waterfalls, rivers, and dense jungle. Multi-day expeditions.",
    distance_km: 20,
    duration_hours: 24,
    facilities: ["Park camps", "Guides"],
    accessibility: "Permit + 4WD recommended",
    best_months: ["Mar", "Apr", "May", "Jun", "Jul", "Aug"],
    latitude: 2.5,
    longitude: 103.3,
    image_url: "/images/location-endau-rompin.jpg",
    is_hidden_gem: true,
    is_family_friendly: false,
    is_pet_friendly: false,
    is_free: false,
    entry_fee: 15,
    avg_rating: 4.7,
    review_count: 95,
    status: "active",
  },
  {
    id: "loc-16",
    name: "Putrajaya Lake Cycling Path",
    state: "Putrajaya",
    activity_types: ["Cycling", "Jogging"],
    difficulty: "Easy",
    description: "Scenic lakeside cycle and jog path around Putrajaya's planned city landscapes.",
    distance_km: 12,
    duration_hours: 1.5,
    facilities: ["Bike rental", "Parking", "Cafes"],
    accessibility: "Open access",
    best_months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    latitude: 2.9264,
    longitude: 101.6964,
    image_url: "/images/location-putrajaya.jpg",
    is_hidden_gem: false,
    is_family_friendly: true,
    is_pet_friendly: true,
    is_free: true,
    entry_fee: 0,
    avg_rating: 4.3,
    review_count: 380,
    status: "active",
  },
];

export const SEED_USERS = [
  {
    id: "user-demo",
    email: "demo@seekmy.local",
    password: "demo123",
    full_name: "Demo Explorer",
    role: "user",
    created_date: new Date().toISOString(),
  },
];

