export const BADGES = [
  {
    id: "first_steps",
    name: "First Steps",
    description: "Complete your first logged activity",
    icon: "🥾",
    type: "activityCount",
    target: 1,
  },
  {
    id: "trail_regular",
    name: "Trail Regular",
    description: "Complete 10 logged activities",
    icon: "🏃",
    type: "activityCount",
    target: 10,
  },
  {
    id: "distance_25",
    name: "25km Explorer",
    description: "Travel a total of 25km across all activities",
    icon: "📍",
    type: "totalDistance",
    target: 25,
  },
  {
    id: "distance_100",
    name: "Century Club",
    description: "Travel a total of 100km across all activities",
    icon: "🏆",
    type: "totalDistance",
    target: 100,
  },
  {
    id: "state_explorer_3",
    name: "State Hopper",
    description: "Log activities in 3 different states",
    icon: "🗺️",
    type: "statesExplored",
    target: 3,
  },
  {
    id: "state_explorer_all",
    name: "Malaysia Conqueror",
    description: "Log activities in all 13 states + 3 federal territories",
    icon: "🇲🇾",
    type: "statesExplored",
    target: 16,
  },
  {
    id: "diver_debut",
    name: "Deep Diver",
    description: "Log your first diving activity",
    icon: "🤿",
    type: "activityTypeCount",
    activityType: "Diving",
    target: 1,
  },
];